import type { GrammarExercise } from '@/types/grammar-quiz'

export const GRAMMAR_EXERCISES: GrammarExercise[] = [
  // ===========================================================================
  // N5 PARTICLES
  // ===========================================================================
  // は (topic marker)
  {
    id: 'wa-fib-1',
    pattern: 'は',
    type: 'fill_in_blank',
    sentence: '私＿＿＿学生です。',
    english: 'I am a student.',
    correctAnswer: 'は',
    options: ['は', 'が', 'を', 'に'],
    explanation: 'は marks the topic of the sentence — "as for me, I am a student."',
  },
  {
    id: 'wa-fib-2',
    pattern: 'は',
    type: 'fill_in_blank',
    sentence: '今日＿＿＿暑いです。',
    english: 'Today is hot.',
    correctAnswer: 'は',
    options: ['は', 'が', 'も', 'で'],
    explanation: 'は sets "today" as the topic being described.',
  },
  {
    id: 'wa-fib-3',
    pattern: 'は',
    type: 'fill_in_blank',
    sentence: 'これ＿＿＿本です。',
    english: 'This is a book.',
    correctAnswer: 'は',
    options: ['は', 'が', 'の', 'を'],
    explanation: 'は marks "this" as the topic of identification.',
  },
  {
    id: 'wa-fib-4',
    pattern: 'は',
    type: 'fill_in_blank',
    sentence: '田中さん＿＿＿先生です。',
    english: 'Mr. Tanaka is a teacher.',
    correctAnswer: 'は',
    options: ['は', 'が', 'の', 'も'],
    explanation: 'は marks "Tanaka-san" as the topic being described.',
  },
  {
    id: 'wa-mc-1',
    pattern: 'は',
    type: 'multiple_choice',
    sentence: 'Which particle marks the topic of a sentence?',
    english: 'Select the topic marker particle.',
    correctAnswer: 'は',
    options: ['は', 'が', 'を', 'に'],
    explanation: 'は (wa) marks the topic — what the sentence is about.',
  },
  {
    id: 'wa-mc-2',
    pattern: 'は',
    type: 'multiple_choice',
    sentence: 'How is は pronounced when used as a particle?',
    english: 'Select the correct pronunciation.',
    correctAnswer: 'wa',
    options: ['wa', 'ha', 'ba', 'pa'],
    explanation: 'は is pronounced "wa" (not "ha") when used as a particle.',
  },
  {
    id: 'wa-mc-3',
    pattern: 'は',
    type: 'multiple_choice',
    sentence: 'What does は indicate about the information it marks?',
    english: 'Select the best description.',
    correctAnswer: 'Known/old information',
    options: ['Known/old information', 'New information', 'The direct object', 'The location'],
    explanation: 'は marks known/old information as the topic, while が marks new information.',
  },
  // が (subject marker)
  {
    id: 'ga-fib-1',
    pattern: 'が',
    type: 'fill_in_blank',
    sentence: '誰＿＿＿来ましたか。',
    english: 'Who came?',
    correctAnswer: 'が',
    options: ['が', 'は', 'を', 'に'],
    explanation: 'が is required after question words like 誰 (who).',
  },
  {
    id: 'ga-fib-2',
    pattern: 'が',
    type: 'fill_in_blank',
    sentence: '猫＿＿＿好きです。',
    english: 'I like cats.',
    correctAnswer: 'が',
    options: ['が', 'は', 'を', 'の'],
    explanation: 'が marks the object of liking with 好き.',
  },
  {
    id: 'ga-fib-3',
    pattern: 'が',
    type: 'fill_in_blank',
    sentence: '雨＿＿＿降っています。',
    english: 'It is raining.',
    correctAnswer: 'が',
    options: ['が', 'は', 'を', 'で'],
    explanation: 'が marks the subject performing the action (rain falling).',
  },
  {
    id: 'ga-fib-4',
    pattern: 'が',
    type: 'fill_in_blank',
    sentence: '日本語＿＿＿できます。',
    english: 'I can speak Japanese.',
    correctAnswer: 'が',
    options: ['が', 'は', 'を', 'に'],
    explanation: 'が marks the object of ability with できる.',
  },
  {
    id: 'ga-mc-1',
    pattern: 'が',
    type: 'multiple_choice',
    sentence: 'Which particle is required after question words like 誰?',
    english: 'Select the correct particle.',
    correctAnswer: 'が',
    options: ['が', 'は', 'を', 'の'],
    explanation: 'After question words (誰, 何), always use が, not は.',
  },
  {
    id: 'ga-mc-2',
    pattern: 'が',
    type: 'multiple_choice',
    sentence: 'What type of information does が typically mark?',
    english: 'Select the best description.',
    correctAnswer: 'New/important information',
    options: ['New/important information', 'Old/known information', 'The location', 'The time'],
    explanation: 'が highlights new or important information, answering "who?" or "what?".',
  },
  {
    id: 'ga-mc-3',
    pattern: 'が',
    type: 'multiple_choice',
    sentence: 'With which adjective is が used instead of を?',
    english: 'Select the adjective that takes が.',
    correctAnswer: '好き (like)',
    options: ['好き (like)', '大きい (big)', '新しい (new)', '早い (fast)'],
    explanation: '好き, 嫌い, 欲しい, and できる all take が instead of を.',
  },
  // を (direct object)
  {
    id: 'wo-fib-1',
    pattern: 'を',
    type: 'fill_in_blank',
    sentence: '水＿＿＿飲みます。',
    english: 'I drink water.',
    correctAnswer: 'を',
    options: ['を', 'が', 'は', 'に'],
    explanation: 'を marks "water" as the direct object of "drink."',
  },
  {
    id: 'wo-fib-2',
    pattern: 'を',
    type: 'fill_in_blank',
    sentence: '本＿＿＿読みます。',
    english: 'I read a book.',
    correctAnswer: 'を',
    options: ['を', 'が', 'に', 'で'],
    explanation: 'を marks "book" as the direct object of "read."',
  },
  {
    id: 'wo-fib-3',
    pattern: 'を',
    type: 'fill_in_blank',
    sentence: 'テレビ＿＿＿見ます。',
    english: 'I watch TV.',
    correctAnswer: 'を',
    options: ['を', 'が', 'は', 'で'],
    explanation: 'を marks "TV" as the direct object of "watch."',
  },
  {
    id: 'wo-mc-1',
    pattern: 'を',
    type: 'multiple_choice',
    sentence: 'Which particle marks the direct object of an action?',
    english: 'Select the direct object marker.',
    correctAnswer: 'を',
    options: ['を', 'が', 'に', 'で'],
    explanation: 'を marks what receives the action of the verb.',
  },
  {
    id: 'wo-mc-2',
    pattern: 'を',
    type: 'multiple_choice',
    sentence: 'In 公園を歩きます, what does を indicate?',
    english: 'I walk through the park.',
    correctAnswer: 'The space traversed',
    options: ['The space traversed', 'The destination', 'The starting point', 'The tool used'],
    explanation: 'を can mark the space through which movement occurs.',
  },
  {
    id: 'wo-mc-3',
    pattern: 'を',
    type: 'multiple_choice',
    sentence: 'How is を pronounced?',
    english: 'Select the correct pronunciation.',
    correctAnswer: 'o',
    options: ['o', 'wo', 'no', 'to'],
    explanation: 'を is pronounced "o" in modern Japanese, same as お.',
  },
  // に (target/location/time)
  {
    id: 'ni-fib-1',
    pattern: 'に',
    type: 'fill_in_blank',
    sentence: '学校＿＿＿行きます。',
    english: 'I go to school.',
    correctAnswer: 'に',
    options: ['に', 'で', 'を', 'へ'],
    explanation: 'に marks the destination/target of movement.',
  },
  {
    id: 'ni-fib-2',
    pattern: 'に',
    type: 'fill_in_blank',
    sentence: '七時＿＿＿起きます。',
    english: 'I wake up at 7 o\'clock.',
    correctAnswer: 'に',
    options: ['に', 'で', 'は', 'を'],
    explanation: 'に marks specific times.',
  },
  {
    id: 'ni-fib-3',
    pattern: 'に',
    type: 'fill_in_blank',
    sentence: '友達＿＿＿会います。',
    english: 'I meet a friend.',
    correctAnswer: 'に',
    options: ['に', 'を', 'が', 'と'],
    explanation: 'に marks the person you meet with 会う.',
  },
  {
    id: 'ni-fib-4',
    pattern: 'に',
    type: 'fill_in_blank',
    sentence: '椅子＿＿＿座ります。',
    english: 'I sit on a chair.',
    correctAnswer: 'に',
    options: ['に', 'で', 'を', 'が'],
    explanation: 'に marks the surface/place where you sit.',
  },
  {
    id: 'ni-mc-1',
    pattern: 'に',
    type: 'multiple_choice',
    sentence: 'Which use of に is correct?',
    english: 'Select all that apply.',
    correctAnswer: 'All of the above',
    options: ['All of the above', 'Destination only', 'Time only', 'Location only'],
    explanation: 'に marks destinations, specific times, and locations of existence.',
  },
  {
    id: 'ni-mc-2',
    pattern: 'に',
    type: 'multiple_choice',
    sentence: 'Which time expression does NOT take に?',
    english: 'Select the exception.',
    correctAnswer: '今日 (today)',
    options: ['今日 (today)', '三時 (3 o\'clock)', '月曜日 (Monday)', '一月 (January)'],
    explanation: 'Relative time words (今日, 昨日, 明日) don\'t take に.',
  },
  {
    id: 'ni-mc-3',
    pattern: 'に',
    type: 'multiple_choice',
    sentence: 'What does に indicate in 東京に住んでいます?',
    english: 'I live in Tokyo.',
    correctAnswer: 'Location of existence',
    options: ['Location of existence', 'Destination', 'Time', 'Means'],
    explanation: 'に marks where someone exists/lives.',
  },
  // で (location of action / means)
  {
    id: 'de-fib-1',
    pattern: 'で',
    type: 'fill_in_blank',
    sentence: '図書館＿＿＿勉強します。',
    english: 'I study at the library.',
    correctAnswer: 'で',
    options: ['で', 'に', 'を', 'は'],
    explanation: 'で marks where an action takes place.',
  },
  {
    id: 'de-fib-2',
    pattern: 'で',
    type: 'fill_in_blank',
    sentence: 'バス＿＿＿行きます。',
    english: 'I go by bus.',
    correctAnswer: 'で',
    options: ['で', 'に', 'を', 'が'],
    explanation: 'で marks the means/method of transportation.',
  },
  {
    id: 'de-fib-3',
    pattern: 'で',
    type: 'fill_in_blank',
    sentence: '日本語＿＿＿話してください。',
    english: 'Please speak in Japanese.',
    correctAnswer: 'で',
    options: ['で', 'に', 'を', 'が'],
    explanation: 'で marks the language/means used.',
  },
  {
    id: 'de-mc-1',
    pattern: 'で',
    type: 'multiple_choice',
    sentence: 'What is the main difference between に and で for locations?',
    english: 'Select the best explanation.',
    correctAnswer: 'に = existence, で = action',
    options: ['に = existence, で = action', 'に = action, で = existence', 'They are the same', 'で is more formal'],
    explanation: 'に marks where something exists; で marks where an action happens.',
  },
  {
    id: 'de-mc-2',
    pattern: 'で',
    type: 'multiple_choice',
    sentence: 'Which sentence correctly uses で?',
    english: 'Select the correct usage.',
    correctAnswer: 'レストランで食べます',
    options: ['レストランで食べます', 'レストランに食べます', 'レストランを食べます', 'レストランが食べます'],
    explanation: 'で marks where the action of eating takes place.',
  },
  {
    id: 'de-mc-3',
    pattern: 'で',
    type: 'multiple_choice',
    sentence: 'In 箸で食べます, what does で indicate?',
    english: 'I eat with chopsticks.',
    correctAnswer: 'The tool/instrument used',
    options: ['The tool/instrument used', 'The location', 'The time', 'The reason'],
    explanation: 'で marks the tool or instrument used to perform an action.',
  },
  // へ (direction)
  {
    id: 'e-fib-1',
    pattern: 'へ',
    type: 'fill_in_blank',
    sentence: '東京＿＿＿行きます。',
    english: 'I go toward Tokyo.',
    correctAnswer: 'へ',
    options: ['へ', 'で', 'を', 'が'],
    explanation: 'へ marks the direction of movement.',
  },
  {
    id: 'e-fib-2',
    pattern: 'へ',
    type: 'fill_in_blank',
    sentence: '南＿＿＿向かいます。',
    english: 'I head south.',
    correctAnswer: 'へ',
    options: ['へ', 'に', 'で', 'を'],
    explanation: 'へ emphasizes the direction of heading.',
  },
  {
    id: 'e-fib-3',
    pattern: 'へ',
    type: 'fill_in_blank',
    sentence: '日本＿＿＿ようこそ。',
    english: 'Welcome to Japan.',
    correctAnswer: 'へ',
    options: ['へ', 'に', 'で', 'が'],
    explanation: 'へ is used in the set phrase ～へようこそ (welcome to).',
  },
  {
    id: 'e-mc-1',
    pattern: 'へ',
    type: 'multiple_choice',
    sentence: 'How is へ pronounced when used as a particle?',
    english: 'Select the correct pronunciation.',
    correctAnswer: 'e',
    options: ['e', 'he', 'be', 'pe'],
    explanation: 'へ is pronounced "e" (not "he") when used as a particle.',
  },
  {
    id: 'e-mc-2',
    pattern: 'へ',
    type: 'multiple_choice',
    sentence: 'What is the difference between に and へ for destinations?',
    english: 'Select the best explanation.',
    correctAnswer: 'へ emphasizes direction, に the arrival point',
    options: ['へ emphasizes direction, に the arrival point', 'They cannot be interchanged', 'へ is for places, に for people', 'に is casual, へ is formal'],
    explanation: 'へ emphasizes the direction/journey; に emphasizes the destination itself.',
  },
  {
    id: 'e-mc-3',
    pattern: 'へ',
    type: 'multiple_choice',
    sentence: 'Which verb is commonly used with へ?',
    english: 'Select the best match.',
    correctAnswer: '行く (to go)',
    options: ['行く (to go)', '食べる (to eat)', '見る (to see)', '飲む (to drink)'],
    explanation: 'へ is used with movement verbs like 行く, 来る, 帰る.',
  },
  // と (and / with / quotation)
  {
    id: 'to-fib-1',
    pattern: 'と',
    type: 'fill_in_blank',
    sentence: '犬＿＿＿猫が好きです。',
    english: 'I like dogs and cats.',
    correctAnswer: 'と',
    options: ['と', 'や', 'も', 'が'],
    explanation: 'と connects nouns exhaustively (dogs AND cats, nothing else implied).',
  },
  {
    id: 'to-fib-2',
    pattern: 'と',
    type: 'fill_in_blank',
    sentence: '友達＿＿＿映画を見ました。',
    english: 'I watched a movie with a friend.',
    correctAnswer: 'と',
    options: ['と', 'に', 'で', 'が'],
    explanation: 'と marks the person you do an action with.',
  },
  {
    id: 'to-fib-3',
    pattern: 'と',
    type: 'fill_in_blank',
    sentence: '先生は「静かに」＿＿＿言いました。',
    english: 'The teacher said "be quiet."',
    correctAnswer: 'と',
    options: ['と', 'を', 'が', 'に'],
    explanation: 'と marks quoted speech.',
  },
  {
    id: 'to-mc-1',
    pattern: 'と',
    type: 'multiple_choice',
    sentence: 'Which function does と NOT have?',
    english: 'Select the incorrect usage.',
    correctAnswer: 'Marking the topic',
    options: ['Marking the topic', 'Listing nouns (and)', 'Doing with someone', 'Quotation'],
    explanation: 'と lists nouns, marks companionship, and quotes. は marks the topic.',
  },
  {
    id: 'to-mc-2',
    pattern: 'と',
    type: 'multiple_choice',
    sentence: 'What is the difference between と and や for "and"?',
    english: 'Select the best explanation.',
    correctAnswer: 'と is exhaustive, や is partial',
    options: ['と is exhaustive, や is partial', 'と is casual, や is formal', 'They are identical', 'と is for people, や for things'],
    explanation: 'と lists all items; や implies there are more items not listed.',
  },
  {
    id: 'to-mc-3',
    pattern: 'と',
    type: 'multiple_choice',
    sentence: 'In 春になると桜が咲く, what does と mean?',
    english: 'When spring comes, cherry blossoms bloom.',
    correctAnswer: 'When/if (natural consequence)',
    options: ['When/if (natural consequence)', 'And', 'With', 'Quotation'],
    explanation: 'と after a verb expresses a natural/automatic consequence.',
  },
  // も (also)
  {
    id: 'mo-fib-1',
    pattern: 'も',
    type: 'fill_in_blank',
    sentence: '私＿＿＿学生です。',
    english: 'I am also a student.',
    correctAnswer: 'も',
    options: ['も', 'は', 'が', 'を'],
    explanation: 'も replaces は/が to mean "also" or "too."',
  },
  {
    id: 'mo-fib-2',
    pattern: 'も',
    type: 'fill_in_blank',
    sentence: 'コーヒー＿＿＿紅茶＿＿＿好きです。',
    english: 'I like both coffee and tea.',
    correctAnswer: 'も',
    options: ['も', 'は', 'と', 'が'],
    explanation: 'も...も means "both...and" or "neither...nor."',
  },
  {
    id: 'mo-fib-3',
    pattern: 'も',
    type: 'fill_in_blank',
    sentence: '何＿＿＿食べませんでした。',
    english: 'I didn\'t eat anything.',
    correctAnswer: 'も',
    options: ['も', 'を', 'は', 'が'],
    explanation: '何も + negative means "nothing/not anything."',
  },
  {
    id: 'mo-mc-1',
    pattern: 'も',
    type: 'multiple_choice',
    sentence: 'Which particle does も typically replace?',
    english: 'Select the correct answer.',
    correctAnswer: 'は or が',
    options: ['は or が', 'を or で', 'に or へ', 'と or や'],
    explanation: 'も replaces は or が to add "also/too" meaning.',
  },
  {
    id: 'mo-mc-2',
    pattern: 'も',
    type: 'multiple_choice',
    sentence: 'What does 誰も来ませんでした mean?',
    english: 'Select the correct translation.',
    correctAnswer: 'Nobody came',
    options: ['Nobody came', 'Everyone came', 'Someone came', 'Who came?'],
    explanation: '誰も + negative = nobody.',
  },
  {
    id: 'mo-mc-3',
    pattern: 'も',
    type: 'multiple_choice',
    sentence: 'What does どこも in a negative sentence mean?',
    english: 'Select the correct meaning.',
    correctAnswer: 'Nowhere',
    options: ['Nowhere', 'Everywhere', 'Somewhere', 'Here'],
    explanation: 'どこも + negative = nowhere; どこも + positive = everywhere.',
  },

  // ===========================================================================
  // N5 COPULA & EXISTENCE
  // ===========================================================================
  // です
  {
    id: 'desu-fib-1',
    pattern: 'です',
    type: 'fill_in_blank',
    sentence: '私は学生＿＿＿。',
    english: 'I am a student.',
    correctAnswer: 'です',
    options: ['です', 'ます', 'ある', 'いる'],
    explanation: 'です is the polite copula, meaning "is/am/are."',
  },
  {
    id: 'desu-fib-2',
    pattern: 'です',
    type: 'fill_in_blank',
    sentence: 'これは猫＿＿＿。',
    english: 'This is a cat.',
    correctAnswer: 'です',
    options: ['です', 'だ', 'ます', 'ある'],
    explanation: 'です links the topic to a noun in polite speech.',
  },
  {
    id: 'desu-fib-3',
    pattern: 'です',
    type: 'fill_in_blank',
    sentence: '明日は日曜日＿＿＿。',
    english: 'Tomorrow is Sunday.',
    correctAnswer: 'です',
    options: ['です', 'ます', 'いる', 'ある'],
    explanation: 'です states that tomorrow equals Sunday.',
  },
  {
    id: 'desu-mc-1',
    pattern: 'です',
    type: 'multiple_choice',
    sentence: 'What is the plain/casual form of です?',
    english: 'Select the correct form.',
    correctAnswer: 'だ',
    options: ['だ', 'する', 'ある', 'いる'],
    explanation: 'だ is the plain form of the copula です.',
  },
  {
    id: 'desu-mc-2',
    pattern: 'です',
    type: 'multiple_choice',
    sentence: 'What is the past tense of です?',
    english: 'Select the correct form.',
    correctAnswer: 'でした',
    options: ['でした', 'ました', 'だった', 'あった'],
    explanation: 'でした is the polite past copula.',
  },
  {
    id: 'desu-mc-3',
    pattern: 'です',
    type: 'multiple_choice',
    sentence: 'Which word is NOT a form of the copula?',
    english: 'Select the odd one out.',
    correctAnswer: 'ます',
    options: ['ます', 'です', 'だ', 'でした'],
    explanation: 'ます is a polite verb ending, not a copula form.',
  },
  // じゃないです
  {
    id: 'janai-desu-fib-1',
    pattern: 'じゃないです',
    type: 'fill_in_blank',
    sentence: '私は先生＿＿＿。',
    english: 'I am not a teacher.',
    correctAnswer: 'じゃないです',
    options: ['じゃないです', 'です', 'ません', 'くないです'],
    explanation: 'じゃないです negates a noun predicate.',
  },
  {
    id: 'janai-desu-fib-2',
    pattern: 'じゃないです',
    type: 'fill_in_blank',
    sentence: 'これは本＿＿＿。',
    english: 'This is not a book.',
    correctAnswer: 'じゃないです',
    options: ['じゃないです', 'です', 'ません', 'じゃない'],
    explanation: 'じゃないです politely negates "this is a book."',
  },
  {
    id: 'janai-desu-fib-3',
    pattern: 'じゃないです',
    type: 'fill_in_blank',
    sentence: '今日は月曜日＿＿＿。',
    english: 'Today is not Monday.',
    correctAnswer: 'じゃないです',
    options: ['じゃないです', 'です', 'ではありません', 'ません'],
    explanation: 'じゃないです negates the noun "Monday" politely.',
  },
  {
    id: 'janai-desu-mc-1',
    pattern: 'じゃないです',
    type: 'multiple_choice',
    sentence: 'What is the more formal equivalent of じゃないです?',
    english: 'Select the formal form.',
    correctAnswer: 'ではありません',
    options: ['ではありません', 'ません', 'くないです', 'ないです'],
    explanation: 'ではありません is the formal negative copula.',
  },
  {
    id: 'janai-desu-mc-2',
    pattern: 'じゃないです',
    type: 'multiple_choice',
    sentence: 'じゃないです is used to negate what type of predicate?',
    english: 'Select the correct answer.',
    correctAnswer: 'Noun and な-adjective predicates',
    options: ['Noun and な-adjective predicates', 'い-adjective predicates', 'Verb predicates', 'All predicates'],
    explanation: 'じゃないです negates nouns and な-adjectives. い-adjectives use くない.',
  },
  {
    id: 'janai-desu-mc-3',
    pattern: 'じゃないです',
    type: 'multiple_choice',
    sentence: 'What is the plain form of じゃないです?',
    english: 'Select the correct form.',
    correctAnswer: 'じゃない',
    options: ['じゃない', 'ない', 'くない', 'ません'],
    explanation: 'じゃない is the plain/casual negative copula.',
  },
  // があります
  {
    id: 'arimasu-fib-1',
    pattern: 'があります',
    type: 'fill_in_blank',
    sentence: 'テーブルの上に本＿＿＿。',
    english: 'There is a book on the table.',
    correctAnswer: 'があります',
    options: ['があります', 'がいます', 'はあります', 'をあります'],
    explanation: 'があります expresses the existence of inanimate objects.',
  },
  {
    id: 'arimasu-fib-2',
    pattern: 'があります',
    type: 'fill_in_blank',
    sentence: '明日テスト＿＿＿。',
    english: 'There is a test tomorrow.',
    correctAnswer: 'があります',
    options: ['があります', 'がいます', 'です', 'をします'],
    explanation: 'があります expresses that an event exists/occurs.',
  },
  {
    id: 'arimasu-fib-3',
    pattern: 'があります',
    type: 'fill_in_blank',
    sentence: '駅の近くにコンビニ＿＿＿。',
    english: 'There is a convenience store near the station.',
    correctAnswer: 'があります',
    options: ['があります', 'がいます', 'にあります', 'であります'],
    explanation: 'があります states a building exists at a location.',
  },
  {
    id: 'arimasu-mc-1',
    pattern: 'があります',
    type: 'multiple_choice',
    sentence: 'When do you use があります instead of がいます?',
    english: 'Select the correct rule.',
    correctAnswer: 'For inanimate objects and events',
    options: ['For inanimate objects and events', 'For living things', 'For people only', 'For animals only'],
    explanation: 'あります is for non-living things; います is for living things.',
  },
  {
    id: 'arimasu-mc-2',
    pattern: 'があります',
    type: 'multiple_choice',
    sentence: 'Which item would use があります?',
    english: 'Select the correct example.',
    correctAnswer: '車 (car)',
    options: ['車 (car)', '犬 (dog)', '子供 (child)', '魚 (fish)'],
    explanation: 'Cars are inanimate, so they use あります.',
  },
  // がいます
  {
    id: 'imasu-fib-1',
    pattern: 'がいます',
    type: 'fill_in_blank',
    sentence: '庭に猫＿＿＿。',
    english: 'There is a cat in the garden.',
    correctAnswer: 'がいます',
    options: ['がいます', 'があります', 'はいます', 'でいます'],
    explanation: 'がいます expresses the existence of living things.',
  },
  {
    id: 'imasu-fib-2',
    pattern: 'がいます',
    type: 'fill_in_blank',
    sentence: '教室に学生＿＿＿。',
    english: 'There are students in the classroom.',
    correctAnswer: 'がいます',
    options: ['がいます', 'があります', 'はいます', 'をいます'],
    explanation: 'がいます for people (living beings).',
  },
  {
    id: 'imasu-fib-3',
    pattern: 'がいます',
    type: 'fill_in_blank',
    sentence: '兄弟＿＿＿か。',
    english: 'Do you have siblings?',
    correctAnswer: 'がいます',
    options: ['がいます', 'があります', 'はいます', 'です'],
    explanation: 'がいます is used for having family members (living beings).',
  },
  {
    id: 'imasu-mc-1',
    pattern: 'がいます',
    type: 'multiple_choice',
    sentence: 'Which sentence is correct?',
    english: 'Select the grammatically correct sentence.',
    correctAnswer: '池に魚がいます',
    options: ['池に魚がいます', '池に魚があります', '池で魚がいます', '池を魚がいます'],
    explanation: 'Fish are living, so use がいます. Location of existence uses に.',
  },
  {
    id: 'imasu-mc-2',
    pattern: 'がいます',
    type: 'multiple_choice',
    sentence: 'Which would use がいます?',
    english: 'Select the living thing.',
    correctAnswer: '鳥 (bird)',
    options: ['鳥 (bird)', '木 (tree)', '本 (book)', '山 (mountain)'],
    explanation: 'Birds are animals (living), so they use います. Trees use あります.',
  },

  // ===========================================================================
  // N5 VERBS
  // ===========================================================================
  // ます
  {
    id: 'masu-fib-1',
    pattern: 'ます',
    type: 'fill_in_blank',
    sentence: '毎日日本語を勉強し＿＿＿。',
    english: 'I study Japanese every day.',
    correctAnswer: 'ます',
    options: ['ます', 'ません', 'ました', 'る'],
    explanation: 'ます is the polite present/future verb ending.',
  },
  {
    id: 'masu-fib-2',
    pattern: 'ます',
    type: 'fill_in_blank',
    sentence: '朝ごはんを食べ＿＿＿。',
    english: 'I eat breakfast.',
    correctAnswer: 'ます',
    options: ['ます', 'ません', 'ました', 'る'],
    explanation: 'ます makes the verb polite and present tense.',
  },
  {
    id: 'masu-mc-1',
    pattern: 'ます',
    type: 'multiple_choice',
    sentence: 'What does ます indicate about the verb?',
    english: 'Select the best description.',
    correctAnswer: 'Polite, present/future tense',
    options: ['Polite, present/future tense', 'Casual, present tense', 'Polite, past tense', 'Negative'],
    explanation: 'ます is the polite non-past (present/future) verb form.',
  },
  {
    id: 'masu-mc-2',
    pattern: 'ます',
    type: 'multiple_choice',
    sentence: 'What is the ます-stem of 飲む (to drink)?',
    english: 'Select the correct stem.',
    correctAnswer: '飲み',
    options: ['飲み', '飲む', '飲ま', '飲め'],
    explanation: 'For む-verbs, the stem changes to み: 飲む → 飲みます.',
  },
  // ません
  {
    id: 'masen-fib-1',
    pattern: 'ません',
    type: 'fill_in_blank',
    sentence: 'お酒を飲み＿＿＿。',
    english: 'I don\'t drink alcohol.',
    correctAnswer: 'ません',
    options: ['ません', 'ます', 'ました', 'ない'],
    explanation: 'ません is the polite negative present form.',
  },
  {
    id: 'masen-fib-2',
    pattern: 'ません',
    type: 'fill_in_blank',
    sentence: '肉を食べ＿＿＿。',
    english: 'I don\'t eat meat.',
    correctAnswer: 'ません',
    options: ['ません', 'ます', 'ました', 'ない'],
    explanation: 'ません politely negates the verb.',
  },
  {
    id: 'masen-mc-1',
    pattern: 'ません',
    type: 'multiple_choice',
    sentence: 'What tense is ません?',
    english: 'Select the correct answer.',
    correctAnswer: 'Polite negative present/future',
    options: ['Polite negative present/future', 'Polite negative past', 'Casual negative', 'Polite affirmative'],
    explanation: 'ません is polite negative non-past.',
  },
  {
    id: 'masen-mc-2',
    pattern: 'ません',
    type: 'multiple_choice',
    sentence: 'What is the casual equivalent of 食べません?',
    english: 'Select the correct form.',
    correctAnswer: '食べない',
    options: ['食べない', '食べなかった', '食べる', '食べた'],
    explanation: 'The plain negative of 食べる is 食べない.',
  },
  // ました
  {
    id: 'mashita-fib-1',
    pattern: 'ました',
    type: 'fill_in_blank',
    sentence: '昨日映画を見＿＿＿。',
    english: 'I watched a movie yesterday.',
    correctAnswer: 'ました',
    options: ['ました', 'ます', 'ません', 'た'],
    explanation: 'ました is the polite past tense.',
  },
  {
    id: 'mashita-fib-2',
    pattern: 'ました',
    type: 'fill_in_blank',
    sentence: '東京に行き＿＿＿。',
    english: 'I went to Tokyo.',
    correctAnswer: 'ました',
    options: ['ました', 'ます', 'ません', 'た'],
    explanation: 'ました indicates a completed past action politely.',
  },
  {
    id: 'mashita-mc-1',
    pattern: 'ました',
    type: 'multiple_choice',
    sentence: 'What tense does ました express?',
    english: 'Select the correct answer.',
    correctAnswer: 'Polite past affirmative',
    options: ['Polite past affirmative', 'Polite present', 'Polite negative past', 'Casual past'],
    explanation: 'ました is polite past affirmative.',
  },
  {
    id: 'mashita-mc-2',
    pattern: 'ました',
    type: 'multiple_choice',
    sentence: 'Which is the polite past of 書く (to write)?',
    english: 'Select the correct form.',
    correctAnswer: '書きました',
    options: ['書きました', '書きます', '書きません', '書いた'],
    explanation: '書く → 書き (stem) + ました = 書きました.',
  },
  // ませんでした
  {
    id: 'masen-deshita-fib-1',
    pattern: 'ませんでした',
    type: 'fill_in_blank',
    sentence: '昨日学校に行き＿＿＿。',
    english: 'I didn\'t go to school yesterday.',
    correctAnswer: 'ませんでした',
    options: ['ませんでした', 'ました', 'ません', 'なかった'],
    explanation: 'ませんでした is the polite negative past.',
  },
  {
    id: 'masen-deshita-fib-2',
    pattern: 'ませんでした',
    type: 'fill_in_blank',
    sentence: '何も食べ＿＿＿。',
    english: 'I didn\'t eat anything.',
    correctAnswer: 'ませんでした',
    options: ['ませんでした', 'ました', 'ません', 'なかった'],
    explanation: 'ませんでした for polite past negative.',
  },
  {
    id: 'masen-deshita-mc-1',
    pattern: 'ませんでした',
    type: 'multiple_choice',
    sentence: 'What is the casual form of 行きませんでした?',
    english: 'Select the correct form.',
    correctAnswer: '行かなかった',
    options: ['行かなかった', '行った', '行かない', '行きません'],
    explanation: 'The plain negative past of 行く is 行かなかった.',
  },
  // て-form
  {
    id: 'te-form-fib-1',
    pattern: 'て-form',
    type: 'fill_in_blank',
    sentence: '手を洗っ＿＿＿、食べてください。',
    english: 'Please wash your hands and then eat.',
    correctAnswer: 'て',
    options: ['て', 'た', 'で', 'に'],
    explanation: 'て-form connects sequential actions.',
  },
  {
    id: 'te-form-fib-2',
    pattern: 'て-form',
    type: 'fill_in_blank',
    sentence: 'ここに座っ＿＿＿ください。',
    english: 'Please sit here.',
    correctAnswer: 'て',
    options: ['て', 'た', 'を', 'に'],
    explanation: 'て + ください is the polite request form.',
  },
  {
    id: 'te-form-fib-3',
    pattern: 'て-form',
    type: 'fill_in_blank',
    sentence: '写真を撮っ＿＿＿もいいですか。',
    english: 'May I take a photo?',
    correctAnswer: 'て',
    options: ['て', 'た', 'で', 'を'],
    explanation: 'て + もいい asks for permission.',
  },
  {
    id: 'te-form-mc-1',
    pattern: 'て-form',
    type: 'multiple_choice',
    sentence: 'What is the て-form of 読む (to read)?',
    english: 'Select the correct form.',
    correctAnswer: '読んで',
    options: ['読んで', '読んだ', '読みて', '読って'],
    explanation: 'む-verbs: む → んで. 読む → 読んで.',
  },
  {
    id: 'te-form-mc-2',
    pattern: 'て-form',
    type: 'multiple_choice',
    sentence: 'Which is NOT a use of て-form?',
    english: 'Select the incorrect use.',
    correctAnswer: 'Expressing past tense',
    options: ['Expressing past tense', 'Making requests (てください)', 'Connecting actions', 'Asking permission (てもいい)'],
    explanation: 'Past tense uses た-form, not て-form.',
  },
  {
    id: 'te-form-mc-3',
    pattern: 'て-form',
    type: 'multiple_choice',
    sentence: 'What is the て-form of 行く (to go)?',
    english: 'Select the correct irregular form.',
    correctAnswer: '行って',
    options: ['行って', '行いて', '行きて', '行んで'],
    explanation: '行く is irregular: 行く → 行って (not 行いて).',
  },
  // ている
  {
    id: 'teiru-fib-1',
    pattern: 'ている',
    type: 'fill_in_blank',
    sentence: '今、本を読ん＿＿＿います。',
    english: 'I am reading a book now.',
    correctAnswer: 'で',
    options: ['で', 'て', 'だ', 'に'],
    explanation: '読んでいます: て-form of 読む is 読んで + います.',
  },
  {
    id: 'teiru-fib-2',
    pattern: 'ている',
    type: 'fill_in_blank',
    sentence: '東京に住ん＿＿＿います。',
    english: 'I live in Tokyo.',
    correctAnswer: 'で',
    options: ['で', 'て', 'だ', 'た'],
    explanation: '住んでいます expresses an ongoing state of living.',
  },
  {
    id: 'teiru-fib-3',
    pattern: 'ている',
    type: 'fill_in_blank',
    sentence: '雨が降っ＿＿＿います。',
    english: 'It is raining.',
    correctAnswer: 'て',
    options: ['て', 'で', 'た', 'に'],
    explanation: '降っています: て-form of 降る is 降って + います.',
  },
  {
    id: 'teiru-mc-1',
    pattern: 'ている',
    type: 'multiple_choice',
    sentence: 'What does ている express?',
    english: 'Select the best answer.',
    correctAnswer: 'Ongoing action or resultant state',
    options: ['Ongoing action or resultant state', 'Past tense only', 'Future intention', 'Negative action'],
    explanation: 'ている shows an action in progress or a resulting state.',
  },
  {
    id: 'teiru-mc-2',
    pattern: 'ている',
    type: 'multiple_choice',
    sentence: 'What does 結婚しています mean?',
    english: 'Select the correct meaning.',
    correctAnswer: 'Is married (resultant state)',
    options: ['Is married (resultant state)', 'Is getting married now', 'Was married', 'Will get married'],
    explanation: 'With instantaneous verbs, ている shows the resulting state.',
  },

  // ===========================================================================
  // N5 ADJECTIVES
  // ===========================================================================
  // い-adjective
  {
    id: 'i-adj-fib-1',
    pattern: 'い-adjective',
    type: 'fill_in_blank',
    sentence: 'この本は面白＿＿＿です。',
    english: 'This book is interesting.',
    correctAnswer: 'い',
    options: ['い', 'く', 'な', 'に'],
    explanation: 'い-adjectives end in い in their basic form.',
  },
  {
    id: 'i-adj-fib-2',
    pattern: 'い-adjective',
    type: 'fill_in_blank',
    sentence: '大き＿＿＿犬がいます。',
    english: 'There is a big dog.',
    correctAnswer: 'い',
    options: ['い', 'な', 'く', 'の'],
    explanation: 'い-adjectives directly modify nouns with い.',
  },
  {
    id: 'i-adj-fib-3',
    pattern: 'い-adjective',
    type: 'fill_in_blank',
    sentence: '昨日は暑＿＿＿です。',
    english: 'Yesterday was hot.',
    correctAnswer: 'かった',
    options: ['かった', 'い', 'くない', 'くて'],
    explanation: 'Past tense of い-adj: い → かった.',
  },
  {
    id: 'i-adj-mc-1',
    pattern: 'い-adjective',
    type: 'multiple_choice',
    sentence: 'Which is an い-adjective?',
    english: 'Select the い-adjective.',
    correctAnswer: '高い (expensive)',
    options: ['高い (expensive)', '静か (quiet)', '元気 (healthy)', '好き (like)'],
    explanation: '高い ends in い and is a true い-adjective. 静か, 元気, 好き are な-adjectives.',
  },
  {
    id: 'i-adj-mc-2',
    pattern: 'い-adjective',
    type: 'multiple_choice',
    sentence: 'Which word looks like an い-adjective but is actually a な-adjective?',
    english: 'Select the exception.',
    correctAnswer: 'きれい',
    options: ['きれい', '新しい', '古い', '小さい'],
    explanation: 'きれい ends in い but is a な-adjective (きれいな).',
  },
  // な-adjective
  {
    id: 'na-adj-fib-1',
    pattern: 'な-adjective',
    type: 'fill_in_blank',
    sentence: 'ここは静か＿＿＿場所です。',
    english: 'This is a quiet place.',
    correctAnswer: 'な',
    options: ['な', 'い', 'の', 'に'],
    explanation: 'な-adjectives need な when modifying a noun.',
  },
  {
    id: 'na-adj-fib-2',
    pattern: 'な-adjective',
    type: 'fill_in_blank',
    sentence: '日本語が上手＿＿＿ですね。',
    english: 'You\'re good at Japanese, aren\'t you?',
    correctAnswer: '',
    options: ['', 'な', 'い', 'く'],
    explanation: 'な-adjectives use です directly (上手です), no な before です.',
  },
  {
    id: 'na-adj-fib-3',
    pattern: 'な-adjective',
    type: 'fill_in_blank',
    sentence: '元気＿＿＿人が好きです。',
    english: 'I like energetic people.',
    correctAnswer: 'な',
    options: ['な', 'い', 'の', 'に'],
    explanation: 'な-adjectives require な before nouns: 元気な人.',
  },
  {
    id: 'na-adj-mc-1',
    pattern: 'な-adjective',
    type: 'multiple_choice',
    sentence: 'How do you make a な-adjective past tense?',
    english: 'Select the correct pattern.',
    correctAnswer: 'な-adj + でした',
    options: ['な-adj + でした', 'な-adj + かった', 'な-adj + ました', 'な-adj + た'],
    explanation: 'な-adjectives use でした for past: 静かでした.',
  },
  {
    id: 'na-adj-mc-2',
    pattern: 'な-adjective',
    type: 'multiple_choice',
    sentence: 'Which is a な-adjective?',
    english: 'Select the な-adjective.',
    correctAnswer: '好き (like)',
    options: ['好き (like)', '高い (tall)', '長い (long)', '早い (fast)'],
    explanation: '好き is a な-adjective: 好きな食べ物.',
  },
  // くない
  {
    id: 'kunai-fib-1',
    pattern: 'くない',
    type: 'fill_in_blank',
    sentence: 'この映画は面白＿＿＿です。',
    english: 'This movie is not interesting.',
    correctAnswer: 'くない',
    options: ['くない', 'い', 'かった', 'くて'],
    explanation: 'い-adjective negative: い → くない.',
  },
  {
    id: 'kunai-fib-2',
    pattern: 'くない',
    type: 'fill_in_blank',
    sentence: '今日は寒＿＿＿です。',
    english: 'Today is not cold.',
    correctAnswer: 'くない',
    options: ['くない', 'い', 'かった', 'くて'],
    explanation: '寒い → 寒くない (not cold).',
  },
  {
    id: 'kunai-mc-1',
    pattern: 'くない',
    type: 'multiple_choice',
    sentence: 'What is the negative of いい (good)?',
    english: 'Select the correct form.',
    correctAnswer: 'よくない',
    options: ['よくない', 'いくない', 'いいじゃない', 'よくありません'],
    explanation: 'いい is irregular: negative is よくない (from よい).',
  },
  {
    id: 'kunai-mc-2',
    pattern: 'くない',
    type: 'multiple_choice',
    sentence: 'What is the negative past of 高い?',
    english: 'Select the correct form.',
    correctAnswer: '高くなかった',
    options: ['高くなかった', '高くない', '高かった', '高いじゃなかった'],
    explanation: 'い-adj negative past: い → くなかった.',
  },
  // じゃない
  {
    id: 'janai-fib-1',
    pattern: 'じゃない',
    type: 'fill_in_blank',
    sentence: 'この部屋は静か＿＿＿。',
    english: 'This room is not quiet. (casual)',
    correctAnswer: 'じゃない',
    options: ['じゃない', 'くない', 'ない', 'ません'],
    explanation: 'な-adjective casual negative: stem + じゃない.',
  },
  {
    id: 'janai-fib-2',
    pattern: 'じゃない',
    type: 'fill_in_blank',
    sentence: '彼は学生＿＿＿。',
    english: 'He is not a student. (casual)',
    correctAnswer: 'じゃない',
    options: ['じゃない', 'くない', 'ない', 'ません'],
    explanation: 'Noun casual negative: noun + じゃない.',
  },
  {
    id: 'janai-mc-1',
    pattern: 'じゃない',
    type: 'multiple_choice',
    sentence: 'じゃない is the plain negative of what?',
    english: 'Select the correct answer.',
    correctAnswer: 'です (copula)',
    options: ['です (copula)', 'ます (polite verb)', 'い-adjective', 'ある (exist)'],
    explanation: 'じゃない negates nouns and な-adjectives (plain form of じゃないです).',
  },

  // ===========================================================================
  // N5 SENTENCE PATTERNS
  // ===========================================================================
  // か
  {
    id: 'ka-fib-1',
    pattern: 'か',
    type: 'fill_in_blank',
    sentence: 'これは何です＿＿＿。',
    english: 'What is this?',
    correctAnswer: 'か',
    options: ['か', 'ね', 'よ', 'の'],
    explanation: 'か turns a statement into a question.',
  },
  {
    id: 'ka-fib-2',
    pattern: 'か',
    type: 'fill_in_blank',
    sentence: '明日は暇です＿＿＿。',
    english: 'Are you free tomorrow?',
    correctAnswer: 'か',
    options: ['か', 'ね', 'よ', 'な'],
    explanation: 'か at the end makes it a yes/no question.',
  },
  {
    id: 'ka-mc-1',
    pattern: 'か',
    type: 'multiple_choice',
    sentence: 'In casual speech, how is a question often formed without か?',
    english: 'Select the correct answer.',
    correctAnswer: 'Rising intonation only',
    options: ['Rising intonation only', 'Adding ね', 'Adding よ', 'Changing word order'],
    explanation: 'In casual Japanese, rising intonation alone marks a question.',
  },
  {
    id: 'ka-mc-2',
    pattern: 'か',
    type: 'multiple_choice',
    sentence: 'What does か do when added to question words (e.g., 何か)?',
    english: 'Select the correct meaning.',
    correctAnswer: 'Makes it indefinite (something)',
    options: ['Makes it indefinite (something)', 'Makes it a question', 'Negates the word', 'Adds emphasis'],
    explanation: '何か = something, 誰か = someone, どこか = somewhere.',
  },
  // の
  {
    id: 'no-fib-1',
    pattern: 'の',
    type: 'fill_in_blank',
    sentence: '私＿＿＿本です。',
    english: 'It is my book.',
    correctAnswer: 'の',
    options: ['の', 'は', 'が', 'を'],
    explanation: 'の shows possession: 私の本 = my book.',
  },
  {
    id: 'no-fib-2',
    pattern: 'の',
    type: 'fill_in_blank',
    sentence: '日本語＿＿＿先生です。',
    english: 'A Japanese language teacher.',
    correctAnswer: 'の',
    options: ['の', 'は', 'が', 'に'],
    explanation: 'の connects nouns: 日本語の先生 = teacher of Japanese.',
  },
  {
    id: 'no-mc-1',
    pattern: 'の',
    type: 'multiple_choice',
    sentence: 'What does の do between two nouns?',
    english: 'Select the best description.',
    correctAnswer: 'Shows possession or association',
    options: ['Shows possession or association', 'Marks the subject', 'Shows direction', 'Marks the object'],
    explanation: 'の connects nouns: A の B = B of A, A\'s B.',
  },
  {
    id: 'no-mc-2',
    pattern: 'の',
    type: 'multiple_choice',
    sentence: 'What does 食べるのが好き mean?',
    english: 'Select the correct translation.',
    correctAnswer: 'I like eating',
    options: ['I like eating', 'I eat what I like', 'I like food', 'I don\'t eat'],
    explanation: 'の nominalizes verbs: 食べるの = the act of eating.',
  },
  // ね
  {
    id: 'ne-fib-1',
    pattern: 'ね',
    type: 'fill_in_blank',
    sentence: 'いい天気です＿＿＿。',
    english: 'Nice weather, isn\'t it?',
    correctAnswer: 'ね',
    options: ['ね', 'か', 'よ', 'の'],
    explanation: 'ね seeks agreement from the listener.',
  },
  {
    id: 'ne-fib-2',
    pattern: 'ね',
    type: 'fill_in_blank',
    sentence: 'この料理は美味しいです＿＿＿。',
    english: 'This food is delicious, isn\'t it?',
    correctAnswer: 'ね',
    options: ['ね', 'か', 'よ', 'の'],
    explanation: 'ね invites the listener to agree.',
  },
  {
    id: 'ne-mc-1',
    pattern: 'ね',
    type: 'multiple_choice',
    sentence: 'What function does ね serve?',
    english: 'Select the best description.',
    correctAnswer: 'Seeking agreement or confirmation',
    options: ['Seeking agreement or confirmation', 'Asserting new information', 'Asking a question', 'Expressing surprise'],
    explanation: 'ね is like "right?", "isn\'t it?" — it seeks shared understanding.',
  },
  // よ
  {
    id: 'yo-fib-1',
    pattern: 'よ',
    type: 'fill_in_blank',
    sentence: 'これは美味しいです＿＿＿。',
    english: 'This is delicious, you know!',
    correctAnswer: 'よ',
    options: ['よ', 'ね', 'か', 'の'],
    explanation: 'よ asserts information the listener doesn\'t know.',
  },
  {
    id: 'yo-fib-2',
    pattern: 'よ',
    type: 'fill_in_blank',
    sentence: '明日は休みです＿＿＿。',
    english: 'Tomorrow is a day off, you know.',
    correctAnswer: 'よ',
    options: ['よ', 'ね', 'か', 'の'],
    explanation: 'よ shares information the listener may not know.',
  },
  {
    id: 'yo-mc-1',
    pattern: 'よ',
    type: 'multiple_choice',
    sentence: 'What is the difference between ね and よ?',
    english: 'Select the best explanation.',
    correctAnswer: 'ね seeks agreement, よ asserts information',
    options: ['ね seeks agreement, よ asserts information', 'They are the same', 'ね is formal, よ is casual', 'よ is a question marker'],
    explanation: 'ね = shared info (right?); よ = new info (I\'m telling you).',
  },

  // ===========================================================================
  // N5 CONNECTORS
  // ===========================================================================
  // から
  {
    id: 'kara-fib-1',
    pattern: 'から',
    type: 'fill_in_blank',
    sentence: '暑いです＿＿＿、窓を開けます。',
    english: 'Because it\'s hot, I\'ll open the window.',
    correctAnswer: 'から',
    options: ['から', 'けど', 'ので', 'のに'],
    explanation: 'から gives the reason "because."',
  },
  {
    id: 'kara-fib-2',
    pattern: 'から',
    type: 'fill_in_blank',
    sentence: '九時＿＿＿仕事です。',
    english: 'Work starts from 9 o\'clock.',
    correctAnswer: 'から',
    options: ['から', 'まで', 'に', 'で'],
    explanation: 'から after a noun/time means "from."',
  },
  {
    id: 'kara-mc-1',
    pattern: 'から',
    type: 'multiple_choice',
    sentence: 'What are the two meanings of から?',
    english: 'Select the correct answer.',
    correctAnswer: 'Because (after clause) and from (after noun)',
    options: ['Because (after clause) and from (after noun)', 'But and until', 'If and when', 'And and or'],
    explanation: 'から = "because" after a sentence, "from" after a noun/time.',
  },
  // けど / が
  {
    id: 'kedo-fib-1',
    pattern: 'けど / が',
    type: 'fill_in_blank',
    sentence: '日本語は難しいです＿＿＿、面白いです。',
    english: 'Japanese is difficult, but interesting.',
    correctAnswer: 'が',
    options: ['が', 'から', 'ので', 'のに'],
    explanation: 'が connects contrasting clauses ("but").',
  },
  {
    id: 'kedo-fib-2',
    pattern: 'けど / が',
    type: 'fill_in_blank',
    sentence: '高い＿＿＿、買いました。',
    english: 'It was expensive, but I bought it.',
    correctAnswer: 'けど',
    options: ['けど', 'から', 'ので', 'のに'],
    explanation: 'けど is the casual form of "but."',
  },
  {
    id: 'kedo-mc-1',
    pattern: 'けど / が',
    type: 'multiple_choice',
    sentence: 'Which is more formal: けど or が?',
    english: 'Select the correct answer.',
    correctAnswer: 'が is more formal',
    options: ['が is more formal', 'けど is more formal', 'They are equally formal', 'Neither is formal'],
    explanation: 'が is slightly more formal; けど is casual. Both mean "but."',
  },
  // たい
  {
    id: 'tai-fib-1',
    pattern: 'たい',
    type: 'fill_in_blank',
    sentence: '日本に行き＿＿＿です。',
    english: 'I want to go to Japan.',
    correctAnswer: 'たい',
    options: ['たい', 'ます', 'ません', 'ている'],
    explanation: 'Verb stem + たい = want to do.',
  },
  {
    id: 'tai-fib-2',
    pattern: 'たい',
    type: 'fill_in_blank',
    sentence: '何を食べ＿＿＿ですか。',
    english: 'What do you want to eat?',
    correctAnswer: 'たい',
    options: ['たい', 'ます', 'ました', 'ている'],
    explanation: '食べたい = want to eat.',
  },
  {
    id: 'tai-fib-3',
    pattern: 'たい',
    type: 'fill_in_blank',
    sentence: '今日は何もし＿＿＿くないです。',
    english: 'I don\'t want to do anything today.',
    correctAnswer: 'た',
    options: ['た', 'ま', 'て', 'い'],
    explanation: 'したくない = don\'t want to do. し + たい → したくない (negative).',
  },
  {
    id: 'tai-mc-1',
    pattern: 'たい',
    type: 'multiple_choice',
    sentence: 'How does たい conjugate?',
    english: 'Select the correct answer.',
    correctAnswer: 'Like an い-adjective',
    options: ['Like an い-adjective', 'Like a verb', 'Like a な-adjective', 'It doesn\'t conjugate'],
    explanation: 'たい conjugates like い-adj: たくない, たかった, たくなかった.',
  },
  {
    id: 'tai-mc-2',
    pattern: 'たい',
    type: 'multiple_choice',
    sentence: 'Can you use たい for other people\'s desires?',
    english: 'Select the correct answer.',
    correctAnswer: 'No, use たがっている for third person',
    options: ['No, use たがっている for third person', 'Yes, always', 'Only in questions', 'Only in negative'],
    explanation: 'たい is for speaker\'s desires. Third person uses たがっている.',
  },
  // ましょう
  {
    id: 'mashou-fib-1',
    pattern: 'ましょう',
    type: 'fill_in_blank',
    sentence: '一緒に食べ＿＿＿。',
    english: 'Let\'s eat together.',
    correctAnswer: 'ましょう',
    options: ['ましょう', 'ます', 'ません', 'ました'],
    explanation: 'ましょう suggests doing something together.',
  },
  {
    id: 'mashou-fib-2',
    pattern: 'ましょう',
    type: 'fill_in_blank',
    sentence: '始め＿＿＿。',
    english: 'Let\'s begin.',
    correctAnswer: 'ましょう',
    options: ['ましょう', 'ます', 'ません', 'ました'],
    explanation: 'ましょう proposes the action of beginning.',
  },
  {
    id: 'mashou-mc-1',
    pattern: 'ましょう',
    type: 'multiple_choice',
    sentence: 'What does ましょうか add compared to ましょう?',
    english: 'Select the correct answer.',
    correctAnswer: 'Makes it an offer/suggestion',
    options: ['Makes it an offer/suggestion', 'Makes it past tense', 'Makes it negative', 'Makes it more casual'],
    explanation: 'ましょうか = "Shall I/we?" — an offer or softer suggestion.',
  },

  // ===========================================================================
  // N4 VERBS
  // ===========================================================================
  // 辞書形
  {
    id: 'jisho-fib-1',
    pattern: '辞書形',
    type: 'fill_in_blank',
    sentence: '日本語を＿＿＿ことができます。',
    english: 'I can speak Japanese.',
    correctAnswer: '話す',
    options: ['話す', '話します', '話して', '話した'],
    explanation: 'Dictionary form is used before ことができる.',
  },
  {
    id: 'jisho-fib-2',
    pattern: '辞書形',
    type: 'fill_in_blank',
    sentence: '＿＿＿前に、手を洗います。',
    english: 'Before eating, I wash my hands.',
    correctAnswer: '食べる',
    options: ['食べる', '食べます', '食べて', '食べた'],
    explanation: 'Dictionary form + 前に = before doing.',
  },
  {
    id: 'jisho-fib-3',
    pattern: '辞書形',
    type: 'fill_in_blank',
    sentence: '＿＿＿のが好きです。',
    english: 'I like reading.',
    correctAnswer: '読む',
    options: ['読む', '読みます', '読んで', '読んだ'],
    explanation: 'Dictionary form + の nominalizes the verb.',
  },
  {
    id: 'jisho-mc-1',
    pattern: '辞書形',
    type: 'multiple_choice',
    sentence: 'What is the dictionary form of 飲みます?',
    english: 'Select the correct form.',
    correctAnswer: '飲む',
    options: ['飲む', '飲み', '飲んで', '飲もう'],
    explanation: 'Remove ます and restore the original ending: 飲みます → 飲む.',
  },
  {
    id: 'jisho-mc-2',
    pattern: '辞書形',
    type: 'multiple_choice',
    sentence: 'What is the dictionary form of 書きます?',
    english: 'Select the correct form.',
    correctAnswer: '書く',
    options: ['書く', '書き', '書いて', '書こう'],
    explanation: '書きます → 書く (き-stem → く ending).',
  },
  {
    id: 'jisho-mc-3',
    pattern: '辞書形',
    type: 'multiple_choice',
    sentence: 'Why is it called 辞書形 (dictionary form)?',
    english: 'Select the correct reason.',
    correctAnswer: 'It is the form listed in dictionaries',
    options: ['It is the form listed in dictionaries', 'It is the most polite form', 'It is used only in writing', 'It is the past tense form'],
    explanation: 'Dictionaries list verbs in their plain present/future form.',
  },
  // ない-form
  {
    id: 'nai-form-fib-1',
    pattern: 'ない-form',
    type: 'fill_in_blank',
    sentence: '明日は＿＿＿方がいいです。',
    english: 'It\'s better not to go tomorrow.',
    correctAnswer: '行かない',
    options: ['行かない', '行く', '行った', '行って'],
    explanation: 'ない-form of 行く is 行かない.',
  },
  {
    id: 'nai-form-fib-2',
    pattern: 'ない-form',
    type: 'fill_in_blank',
    sentence: '野菜を＿＿＿と体に悪い。',
    english: 'If you don\'t eat vegetables, it\'s bad for your health.',
    correctAnswer: '食べない',
    options: ['食べない', '食べる', '食べた', '食べて'],
    explanation: 'ない-form of 食べる is 食べない.',
  },
  {
    id: 'nai-form-fib-3',
    pattern: 'ない-form',
    type: 'fill_in_blank',
    sentence: 'ここで写真を＿＿＿でください。',
    english: 'Please don\'t take photos here.',
    correctAnswer: '撮らない',
    options: ['撮らない', '撮る', '撮って', '撮った'],
    explanation: 'ないでください = please don\'t.',
  },
  {
    id: 'nai-form-mc-1',
    pattern: 'ない-form',
    type: 'multiple_choice',
    sentence: 'What is the ない-form of する?',
    english: 'Select the correct irregular form.',
    correctAnswer: 'しない',
    options: ['しない', 'すない', 'さない', 'せない'],
    explanation: 'する is irregular: する → しない.',
  },
  {
    id: 'nai-form-mc-2',
    pattern: 'ない-form',
    type: 'multiple_choice',
    sentence: 'What is the ない-form of ある?',
    english: 'Select the correct form.',
    correctAnswer: 'ない',
    options: ['ない', 'あらない', 'ありない', 'あない'],
    explanation: 'ある is special: ある → ない (not あらない).',
  },
  // た-form
  {
    id: 'ta-form-fib-1',
    pattern: 'た-form',
    type: 'fill_in_blank',
    sentence: '昨日友達に＿＿＿。',
    english: 'I met a friend yesterday.',
    correctAnswer: '会った',
    options: ['会った', '会う', '会って', '会わない'],
    explanation: 'た-form of 会う is 会った.',
  },
  {
    id: 'ta-form-fib-2',
    pattern: 'た-form',
    type: 'fill_in_blank',
    sentence: 'もう宿題を＿＿＿。',
    english: 'I already did my homework.',
    correctAnswer: 'した',
    options: ['した', 'する', 'して', 'しない'],
    explanation: 'た-form of する is した.',
  },
  {
    id: 'ta-form-mc-1',
    pattern: 'た-form',
    type: 'multiple_choice',
    sentence: 'What is the た-form of 飲む?',
    english: 'Select the correct form.',
    correctAnswer: '飲んだ',
    options: ['飲んだ', '飲みた', '飲った', '飲いた'],
    explanation: 'む-verbs: む → んだ. 飲む → 飲んだ.',
  },
  {
    id: 'ta-form-mc-2',
    pattern: 'た-form',
    type: 'multiple_choice',
    sentence: 'What is the た-form of 行く?',
    english: 'Select the correct irregular form.',
    correctAnswer: '行った',
    options: ['行った', '行いた', '行きた', '行んだ'],
    explanation: '行く is irregular: 行く → 行った (not 行いた).',
  },
  // たことがある
  {
    id: 'takotogaaru-fib-1',
    pattern: 'たことがある',
    type: 'fill_in_blank',
    sentence: '日本に＿＿＿ことがあります。',
    english: 'I have been to Japan.',
    correctAnswer: '行った',
    options: ['行った', '行く', '行って', '行かない'],
    explanation: 'た-form + ことがある = have experienced.',
  },
  {
    id: 'takotogaaru-fib-2',
    pattern: 'たことがある',
    type: 'fill_in_blank',
    sentence: '寿司を食べた＿＿＿がありますか。',
    english: 'Have you ever eaten sushi?',
    correctAnswer: 'こと',
    options: ['こと', 'もの', 'ところ', 'はず'],
    explanation: 'たことがある uses こと to nominalize the experience.',
  },
  {
    id: 'takotogaaru-fib-3',
    pattern: 'たことがある',
    type: 'fill_in_blank',
    sentence: '富士山に登った＿＿＿があります。',
    english: 'I have climbed Mt. Fuji.',
    correctAnswer: 'こと',
    options: ['こと', 'もの', 'ところ', 'はず'],
    explanation: 'た + こと + がある expresses past experience.',
  },
  {
    id: 'takotogaaru-mc-1',
    pattern: 'たことがある',
    type: 'multiple_choice',
    sentence: 'What verb form comes before ことがある?',
    english: 'Select the correct form.',
    correctAnswer: 'た-form (plain past)',
    options: ['た-form (plain past)', 'ます-form', 'て-form', 'Dictionary form'],
    explanation: 'Always: た-form + ことがある.',
  },
  {
    id: 'takotogaaru-mc-2',
    pattern: 'たことがある',
    type: 'multiple_choice',
    sentence: 'How do you say "I have never eaten natto"?',
    english: 'Select the correct sentence.',
    correctAnswer: '納豆を食べたことがありません',
    options: ['納豆を食べたことがありません', '納豆を食べないことがあります', '納豆を食べることがありません', '納豆を食べなかったことがあります'],
    explanation: 'Negative experience: た + ことがない/ありません.',
  },
  // たり〜たりする
  {
    id: 'tari-fib-1',
    pattern: 'たり〜たりする',
    type: 'fill_in_blank',
    sentence: '週末は本を読ん＿＿＿、映画を見たりします。',
    english: 'On weekends I do things like read books and watch movies.',
    correctAnswer: 'だり',
    options: ['だり', 'でり', 'たり', 'から'],
    explanation: '読む → 読んだ → 読んだり. む-verbs use んだ.',
  },
  {
    id: 'tari-fib-2',
    pattern: 'たり〜たりする',
    type: 'fill_in_blank',
    sentence: '食べ＿＿＿飲んだりしました。',
    english: 'I did things like eating and drinking.',
    correctAnswer: 'たり',
    options: ['たり', 'だり', 'てり', 'から'],
    explanation: '食べる → 食べた → 食べたり.',
  },
  {
    id: 'tari-mc-1',
    pattern: 'たり〜たりする',
    type: 'multiple_choice',
    sentence: 'What does たり〜たりする express?',
    english: 'Select the best description.',
    correctAnswer: 'A non-exhaustive list of activities',
    options: ['A non-exhaustive list of activities', 'A sequential order of actions', 'Only two actions', 'Simultaneous actions'],
    explanation: 'たり〜たりする lists example activities among others.',
  },
  {
    id: 'tari-mc-2',
    pattern: 'たり〜たりする',
    type: 'multiple_choice',
    sentence: 'What form is used to make たり?',
    english: 'Select the correct form.',
    correctAnswer: 'た-form + り',
    options: ['た-form + り', 'て-form + り', 'Dictionary form + り', 'ます-stem + り'],
    explanation: 'Take the た-form and add り: 食べた → 食べたり.',
  },
  // てある
  {
    id: 'tearu-fib-1',
    pattern: 'てある',
    type: 'fill_in_blank',
    sentence: '窓が開け＿＿＿あります。',
    english: 'The window has been opened (and is still open).',
    correctAnswer: 'て',
    options: ['て', 'た', 'で', 'に'],
    explanation: 'て + ある shows a resultant state from intentional action.',
  },
  {
    id: 'tearu-fib-2',
    pattern: 'てある',
    type: 'fill_in_blank',
    sentence: '名前が書い＿＿＿あります。',
    english: 'A name has been written (and remains).',
    correctAnswer: 'て',
    options: ['て', 'た', 'で', 'に'],
    explanation: '書いてある = has been written and still exists.',
  },
  {
    id: 'tearu-mc-1',
    pattern: 'てある',
    type: 'multiple_choice',
    sentence: 'What is the difference between ている and てある?',
    english: 'Select the best explanation.',
    correctAnswer: 'てある implies someone did it intentionally',
    options: ['てある implies someone did it intentionally', 'They mean the same thing', 'ている is more polite', 'てある is past tense'],
    explanation: 'てある = intentional result; ている = ongoing action or natural state.',
  },
  {
    id: 'tearu-mc-2',
    pattern: 'てある',
    type: 'multiple_choice',
    sentence: 'What type of verbs are used with てある?',
    english: 'Select the correct answer.',
    correctAnswer: 'Transitive verbs',
    options: ['Transitive verbs', 'Intransitive verbs', 'Any verb', 'Only する verbs'],
    explanation: 'てある uses transitive verbs (verbs that take を).',
  },
  // てしまう
  {
    id: 'teshimau-fib-1',
    pattern: 'てしまう',
    type: 'fill_in_blank',
    sentence: 'ケーキを全部食べ＿＿＿しまいました。',
    english: 'I ended up eating all the cake.',
    correctAnswer: 'て',
    options: ['て', 'た', 'で', 'に'],
    explanation: 'てしまう expresses regret about completing an action.',
  },
  {
    id: 'teshimau-fib-2',
    pattern: 'てしまう',
    type: 'fill_in_blank',
    sentence: '電車に忘れ物をし＿＿＿しまった。',
    english: 'I accidentally left something on the train.',
    correctAnswer: 'て',
    options: ['て', 'た', 'で', 'に'],
    explanation: 'てしまう can express an unfortunate accident.',
  },
  {
    id: 'teshimau-mc-1',
    pattern: 'てしまう',
    type: 'multiple_choice',
    sentence: 'What two meanings does てしまう have?',
    english: 'Select the correct answer.',
    correctAnswer: 'Completion and regret/accident',
    options: ['Completion and regret/accident', 'Permission and prohibition', 'Ability and inability', 'Desire and obligation'],
    explanation: 'てしまう = completely done (completion) or unfortunately done (regret).',
  },
  {
    id: 'teshimau-mc-2',
    pattern: 'てしまう',
    type: 'multiple_choice',
    sentence: 'What is the casual contracted form of てしまう?',
    english: 'Select the correct contraction.',
    correctAnswer: 'ちゃう',
    options: ['ちゃう', 'ちまう', 'しゃう', 'てまう'],
    explanation: 'てしまう → ちゃう, でしまう → じゃう in casual speech.',
  },
  // 受身形
  {
    id: 'ukemi-fib-1',
    pattern: '受身形',
    type: 'fill_in_blank',
    sentence: '先生に＿＿＿。',
    english: 'I was praised by the teacher.',
    correctAnswer: '褒められた',
    options: ['褒められた', '褒めた', '褒めて', '褒める'],
    explanation: '褒める → 褒められる (passive). に marks the agent.',
  },
  {
    id: 'ukemi-fib-2',
    pattern: '受身形',
    type: 'fill_in_blank',
    sentence: '電車で足を＿＿＿。',
    english: 'I had my foot stepped on in the train.',
    correctAnswer: '踏まれた',
    options: ['踏まれた', '踏んだ', '踏まれて', '踏む'],
    explanation: '踏む → 踏まれる (passive). This is the "suffering passive."',
  },
  {
    id: 'ukemi-mc-1',
    pattern: '受身形',
    type: 'multiple_choice',
    sentence: 'How do you form passive of a る-verb like 食べる?',
    english: 'Select the correct pattern.',
    correctAnswer: '食べられる',
    options: ['食べられる', '食べれる', '食べされる', '食べらる'],
    explanation: 'る-verbs: る → られる. 食べる → 食べられる.',
  },
  {
    id: 'ukemi-mc-2',
    pattern: '受身形',
    type: 'multiple_choice',
    sentence: 'How do you form passive of a う-verb like 読む?',
    english: 'Select the correct pattern.',
    correctAnswer: '読まれる',
    options: ['読まれる', '読みれる', '読むれる', '読められる'],
    explanation: 'う-verbs: change to あ-row + れる. 読む → 読まれる.',
  },
  // 使役形
  {
    id: 'shieki-fib-1',
    pattern: '使役形',
    type: 'fill_in_blank',
    sentence: '母は子供に野菜を＿＿＿。',
    english: 'The mother makes the child eat vegetables.',
    correctAnswer: '食べさせる',
    options: ['食べさせる', '食べられる', '食べる', '食べている'],
    explanation: '食べる → 食べさせる (causative).',
  },
  {
    id: 'shieki-fib-2',
    pattern: '使役形',
    type: 'fill_in_blank',
    sentence: '先生は学生を＿＿＿。',
    english: 'The teacher lets the students go home.',
    correctAnswer: '帰らせた',
    options: ['帰らせた', '帰られた', '帰った', '帰る'],
    explanation: '帰る → 帰らせる (causative). Past: 帰らせた.',
  },
  {
    id: 'shieki-mc-1',
    pattern: '使役形',
    type: 'multiple_choice',
    sentence: 'How do you form causative of a る-verb like 見る?',
    english: 'Select the correct pattern.',
    correctAnswer: '見させる',
    options: ['見させる', '見られる', '見せる', '見させられる'],
    explanation: 'る-verbs: る → させる. 見る → 見させる.',
  },
  {
    id: 'shieki-mc-2',
    pattern: '使役形',
    type: 'multiple_choice',
    sentence: 'What two meanings can causative express?',
    english: 'Select the correct answer.',
    correctAnswer: 'Make someone do / Let someone do',
    options: ['Make someone do / Let someone do', 'Can do / Cannot do', 'Want to / Don\'t want to', 'Should / Shouldn\'t'],
    explanation: 'Causative can mean "force" or "allow" depending on context.',
  },

  // ===========================================================================
  // N4 CONNECTORS
  // ===========================================================================
  // なければならない
  {
    id: 'nakereba-fib-1',
    pattern: 'なければならない',
    type: 'fill_in_blank',
    sentence: '毎日勉強し＿＿＿。',
    english: 'I must study every day.',
    correctAnswer: 'なければならない',
    options: ['なければならない', 'なくてもいい', 'たい', 'ている'],
    explanation: 'しなければならない = must do.',
  },
  {
    id: 'nakereba-fib-2',
    pattern: 'なければならない',
    type: 'fill_in_blank',
    sentence: '明日早く起き＿＿＿。',
    english: 'I have to wake up early tomorrow.',
    correctAnswer: 'なければならない',
    options: ['なければならない', 'なくてもいい', 'たい', 'ましょう'],
    explanation: '起きなければならない = must wake up.',
  },
  {
    id: 'nakereba-mc-1',
    pattern: 'なければならない',
    type: 'multiple_choice',
    sentence: 'What is a shorter way to say なければならない?',
    english: 'Select the common contraction.',
    correctAnswer: 'なきゃ',
    options: ['なきゃ', 'なけりゃ', 'ないと', 'All of the above'],
    explanation: 'なきゃ, なけりゃ, ないと are all casual contractions.',
  },
  {
    id: 'nakereba-mc-2',
    pattern: 'なければならない',
    type: 'multiple_choice',
    sentence: 'What verb form comes before なければならない?',
    english: 'Select the correct form.',
    correctAnswer: 'ない-form (remove ない)',
    options: ['ない-form (remove ない)', 'Dictionary form', 'て-form', 'た-form'],
    explanation: 'Take ない-form, drop ない, add なければならない.',
  },
  // なくてもいい
  {
    id: 'nakutemoii-fib-1',
    pattern: 'なくてもいい',
    type: 'fill_in_blank',
    sentence: '明日は来＿＿＿もいいです。',
    english: 'You don\'t have to come tomorrow.',
    correctAnswer: 'なくて',
    options: ['なくて', 'ないて', 'なくで', 'ないで'],
    explanation: '来る → 来ない → 来なくてもいい.',
  },
  {
    id: 'nakutemoii-fib-2',
    pattern: 'なくてもいい',
    type: 'fill_in_blank',
    sentence: '全部食べ＿＿＿もいいですよ。',
    english: 'You don\'t have to eat everything.',
    correctAnswer: 'なくて',
    options: ['なくて', 'ないで', 'なくで', 'ないて'],
    explanation: '食べる → 食べない → 食べなくてもいい.',
  },
  {
    id: 'nakutemoii-mc-1',
    pattern: 'なくてもいい',
    type: 'multiple_choice',
    sentence: 'What is the opposite of なくてもいい?',
    english: 'Select the opposite expression.',
    correctAnswer: 'なければならない (must do)',
    options: ['なければならない (must do)', 'てもいい (may do)', 'たい (want to)', 'ている (is doing)'],
    explanation: 'なくてもいい = don\'t have to; なければならない = must.',
  },
  // たら
  {
    id: 'tara-fib-1',
    pattern: 'たら',
    type: 'fill_in_blank',
    sentence: '雨が降っ＿＿＿、出かけません。',
    english: 'If it rains, I won\'t go out.',
    correctAnswer: 'たら',
    options: ['たら', 'ても', 'ので', 'から'],
    explanation: 'たら expresses a conditional "if/when."',
  },
  {
    id: 'tara-fib-2',
    pattern: 'たら',
    type: 'fill_in_blank',
    sentence: '家に帰っ＿＿＿、電話してください。',
    english: 'When you get home, please call me.',
    correctAnswer: 'たら',
    options: ['たら', 'ても', 'ので', 'から'],
    explanation: 'たら for "when" — after you return home.',
  },
  {
    id: 'tara-fib-3',
    pattern: 'たら',
    type: 'fill_in_blank',
    sentence: '安かっ＿＿＿、買います。',
    english: 'If it\'s cheap, I\'ll buy it.',
    correctAnswer: 'たら',
    options: ['たら', 'ても', 'ので', 'けど'],
    explanation: 'い-adjective conditional: い → かったら.',
  },
  {
    id: 'tara-mc-1',
    pattern: 'たら',
    type: 'multiple_choice',
    sentence: 'How is たら formed?',
    english: 'Select the correct formation.',
    correctAnswer: 'た-form + ら',
    options: ['た-form + ら', 'Dictionary form + ら', 'ない-form + ら', 'ます-form + ら'],
    explanation: 'Take the た-form and add ら: 行った → 行ったら.',
  },
  // ば-form
  {
    id: 'ba-form-fib-1',
    pattern: 'ば-form',
    type: 'fill_in_blank',
    sentence: '天気がよけ＿＿＿、散歩に行きます。',
    english: 'If the weather is good, I\'ll go for a walk.',
    correctAnswer: 'れば',
    options: ['れば', 'たら', 'ると', 'なら'],
    explanation: 'い-adjective: い → ければ. いい → よければ.',
  },
  {
    id: 'ba-form-fib-2',
    pattern: 'ば-form',
    type: 'fill_in_blank',
    sentence: '早く起き＿＿＿、朝ごはんが食べられます。',
    english: 'If you wake up early, you can eat breakfast.',
    correctAnswer: 'れば',
    options: ['れば', 'たら', 'ると', 'なら'],
    explanation: 'る-verb: る → れば. 起きる → 起きれば.',
  },
  {
    id: 'ba-form-mc-1',
    pattern: 'ば-form',
    type: 'multiple_choice',
    sentence: 'How do you form ば for う-verbs like 行く?',
    english: 'Select the correct pattern.',
    correctAnswer: 'Change う to えば (行けば)',
    options: ['Change う to えば (行けば)', 'Add ば directly (行くば)', 'Change to あば (行かば)', 'Change to いば (行きば)'],
    explanation: 'う-verbs: change the final vowel to え-row + ば.',
  },
  {
    id: 'ba-form-mc-2',
    pattern: 'ば-form',
    type: 'multiple_choice',
    sentence: 'When is ば preferred over たら?',
    english: 'Select the best answer.',
    correctAnswer: 'For general/habitual conditions',
    options: ['For general/habitual conditions', 'For one-time events', 'For past events', 'For requests'],
    explanation: 'ば is better for general truths; たら is more versatile.',
  },
  // のに
  {
    id: 'noni-fib-1',
    pattern: 'のに',
    type: 'fill_in_blank',
    sentence: '薬を飲んだ＿＿＿、熱が下がらない。',
    english: 'Although I took medicine, the fever won\'t go down.',
    correctAnswer: 'のに',
    options: ['のに', 'けど', 'から', 'ので'],
    explanation: 'のに expresses frustration: "despite" or "although."',
  },
  {
    id: 'noni-fib-2',
    pattern: 'のに',
    type: 'fill_in_blank',
    sentence: '一生懸命勉強した＿＿＿、テストに落ちた。',
    english: 'Although I studied hard, I failed the test.',
    correctAnswer: 'のに',
    options: ['のに', 'けど', 'から', 'ので'],
    explanation: 'のに conveys frustration about an unexpected result.',
  },
  {
    id: 'noni-mc-1',
    pattern: 'のに',
    type: 'multiple_choice',
    sentence: 'What emotion does のに typically convey?',
    english: 'Select the best answer.',
    correctAnswer: 'Disappointment or frustration',
    options: ['Disappointment or frustration', 'Happiness', 'Neutrality', 'Excitement'],
    explanation: 'のに implies the speaker is unhappy about the contrast.',
  },
  {
    id: 'noni-mc-2',
    pattern: 'のに',
    type: 'multiple_choice',
    sentence: 'What is the difference between のに and けど?',
    english: 'Select the best explanation.',
    correctAnswer: 'のに implies frustration, けど is neutral',
    options: ['のに implies frustration, けど is neutral', 'They are the same', 'けど is more emotional', 'のに is more formal'],
    explanation: 'のに carries emotional weight; けど is a neutral "but."',
  },

  // ===========================================================================
  // N4 SENTENCE PATTERNS
  // ===========================================================================
  // ことができる
  {
    id: 'kotogadekiru-fib-1',
    pattern: 'ことができる',
    type: 'fill_in_blank',
    sentence: '日本語を話す＿＿＿ができます。',
    english: 'I can speak Japanese.',
    correctAnswer: 'こと',
    options: ['こと', 'もの', 'ところ', 'はず'],
    explanation: 'Dictionary form + ことができる = can do.',
  },
  {
    id: 'kotogadekiru-fib-2',
    pattern: 'ことができる',
    type: 'fill_in_blank',
    sentence: 'ここで泳ぐこと＿＿＿できますか。',
    english: 'Can you swim here?',
    correctAnswer: 'が',
    options: ['が', 'を', 'は', 'に'],
    explanation: 'ことができる: こと + が + できる.',
  },
  {
    id: 'kotogadekiru-mc-1',
    pattern: 'ことができる',
    type: 'multiple_choice',
    sentence: 'What verb form comes before ことができる?',
    english: 'Select the correct form.',
    correctAnswer: 'Dictionary form',
    options: ['Dictionary form', 'ます-form', 'て-form', 'た-form'],
    explanation: 'Always: dictionary form + ことができる.',
  },
  {
    id: 'kotogadekiru-mc-2',
    pattern: 'ことができる',
    type: 'multiple_choice',
    sentence: 'What is another way to express ability besides ことができる?',
    english: 'Select the alternative.',
    correctAnswer: 'Potential form (e.g., 食べられる)',
    options: ['Potential form (e.g., 食べられる)', 'て-form (e.g., 食べて)', 'たい-form (e.g., 食べたい)', 'ている (e.g., 食べている)'],
    explanation: 'The potential form is shorter: 食べることができる = 食べられる.',
  },
  // と思う
  {
    id: 'toomou-fib-1',
    pattern: 'と思う',
    type: 'fill_in_blank',
    sentence: '明日は雨だ＿＿＿思います。',
    english: 'I think it will rain tomorrow.',
    correctAnswer: 'と',
    options: ['と', 'に', 'を', 'が'],
    explanation: 'と quotes the thought before 思う.',
  },
  {
    id: 'toomou-fib-2',
    pattern: 'と思う',
    type: 'fill_in_blank',
    sentence: 'この映画は面白い＿＿＿思います。',
    english: 'I think this movie is interesting.',
    correctAnswer: 'と',
    options: ['と', 'に', 'を', 'か'],
    explanation: 'Plain form + と思う expresses an opinion.',
  },
  {
    id: 'toomou-mc-1',
    pattern: 'と思う',
    type: 'multiple_choice',
    sentence: 'What form comes before と思う?',
    english: 'Select the correct form.',
    correctAnswer: 'Plain/casual form',
    options: ['Plain/casual form', 'Polite ます-form', 'て-form', 'Any form'],
    explanation: 'Use plain form before と思う: 行くと思う, not 行きますと思う.',
  },
  {
    id: 'toomou-mc-2',
    pattern: 'と思う',
    type: 'multiple_choice',
    sentence: 'What does と思っている mean vs と思う?',
    english: 'Select the best explanation.',
    correctAnswer: 'Ongoing/held opinion vs momentary thought',
    options: ['Ongoing/held opinion vs momentary thought', 'They are the same', 'Past vs present thought', 'Formal vs casual'],
    explanation: 'と思っている = have been thinking/believe; と思う = think (now).',
  },
  // そうだ
  {
    id: 'souda-fib-1',
    pattern: 'そうだ',
    type: 'fill_in_blank',
    sentence: 'この料理は美味し＿＿＿です。',
    english: 'This food looks delicious.',
    correctAnswer: 'そう',
    options: ['そう', 'さそう', 'だそう', 'みたい'],
    explanation: 'い-adjective: drop い, add そう. 美味しい → 美味しそう.',
  },
  {
    id: 'souda-fib-2',
    pattern: 'そうだ',
    type: 'fill_in_blank',
    sentence: '明日は雨が降る＿＿＿です。',
    english: 'I heard it will rain tomorrow.',
    correctAnswer: 'そう',
    options: ['そう', 'らしい', 'みたい', 'よう'],
    explanation: 'Plain form + そうだ = hearsay ("I heard that...").',
  },
  {
    id: 'souda-mc-1',
    pattern: 'そうだ',
    type: 'multiple_choice',
    sentence: 'What is the difference between 美味しそう and 美味しいそうだ?',
    english: 'Select the best explanation.',
    correctAnswer: 'Looks delicious vs I heard it\'s delicious',
    options: ['Looks delicious vs I heard it\'s delicious', 'They mean the same', 'Past vs present', 'Formal vs casual'],
    explanation: 'Stem + そう = appearance; plain form + そうだ = hearsay.',
  },
  {
    id: 'souda-mc-2',
    pattern: 'そうだ',
    type: 'multiple_choice',
    sentence: 'What is the appearance そう form of いい (good)?',
    english: 'Select the correct form.',
    correctAnswer: 'よさそう',
    options: ['よさそう', 'いさそう', 'いいそう', 'よそう'],
    explanation: 'いい is irregular: いい → よさそう (not いさそう).',
  },
  // 方がいい
  {
    id: 'hougaii-fib-1',
    pattern: '方がいい',
    type: 'fill_in_blank',
    sentence: '早く寝た＿＿＿がいいですよ。',
    english: 'You\'d better go to bed early.',
    correctAnswer: '方',
    options: ['方', 'こと', 'もの', 'ところ'],
    explanation: 'た-form + 方がいい = had better (advice).',
  },
  {
    id: 'hougaii-fib-2',
    pattern: '方がいい',
    type: 'fill_in_blank',
    sentence: 'お酒を飲まない＿＿＿がいいです。',
    english: 'You\'d better not drink alcohol.',
    correctAnswer: '方',
    options: ['方', 'こと', 'もの', 'ところ'],
    explanation: 'ない-form + 方がいい = had better not.',
  },
  {
    id: 'hougaii-mc-1',
    pattern: '方がいい',
    type: 'multiple_choice',
    sentence: 'For positive advice "you should do X", which form precedes 方がいい?',
    english: 'Select the correct form.',
    correctAnswer: 'た-form',
    options: ['た-form', 'Dictionary form', 'ます-form', 'て-form'],
    explanation: 'Positive advice: た-form + 方がいい (食べた方がいい).',
  },
  {
    id: 'hougaii-mc-2',
    pattern: '方がいい',
    type: 'multiple_choice',
    sentence: 'For negative advice "you shouldn\'t", which form is used?',
    english: 'Select the correct form.',
    correctAnswer: 'ない-form + 方がいい',
    options: ['ない-form + 方がいい', 'た-form + 方が悪い', 'ます-form + 方がいい', 'て-form + 方がいい'],
    explanation: 'Negative: ない-form + 方がいい (食べない方がいい).',
  },

  // ===========================================================================
  // N4 GIVING & RECEIVING
  // ===========================================================================
  // てあげる・てくれる・てもらう
  {
    id: 'giving-fib-1',
    pattern: 'てあげる・てくれる・てもらう',
    type: 'fill_in_blank',
    sentence: '友達に日本語を教え＿＿＿。',
    english: 'I taught Japanese for my friend (as a favor).',
    correctAnswer: 'てあげた',
    options: ['てあげた', 'てくれた', 'てもらった', 'ている'],
    explanation: 'てあげる = do something for someone (speaker gives).',
  },
  {
    id: 'giving-fib-2',
    pattern: 'てあげる・てくれる・てもらう',
    type: 'fill_in_blank',
    sentence: '母が弁当を作っ＿＿＿。',
    english: 'My mother made a lunch box for me.',
    correctAnswer: 'てくれた',
    options: ['てくれた', 'てあげた', 'てもらった', 'ている'],
    explanation: 'てくれる = someone does a favor for the speaker.',
  },
  {
    id: 'giving-fib-3',
    pattern: 'てあげる・てくれる・てもらう',
    type: 'fill_in_blank',
    sentence: '先生に漢字を教え＿＿＿。',
    english: 'I had the teacher teach me kanji.',
    correctAnswer: 'てもらった',
    options: ['てもらった', 'てあげた', 'てくれた', 'ている'],
    explanation: 'てもらう = receive the favor of someone doing something.',
  },
  {
    id: 'giving-mc-1',
    pattern: 'てあげる・てくれる・てもらう',
    type: 'multiple_choice',
    sentence: 'When do you use てくれる instead of てあげる?',
    english: 'Select the correct answer.',
    correctAnswer: 'When someone does a favor FOR the speaker',
    options: ['When someone does a favor FOR the speaker', 'When the speaker does a favor', 'When requesting a favor', 'They are interchangeable'],
    explanation: 'てくれる: favor flows toward the speaker; てあげる: away from.',
  },
  {
    id: 'giving-mc-2',
    pattern: 'てあげる・てくれる・てもらう',
    type: 'multiple_choice',
    sentence: 'How do you politely ask someone to do something using this pattern?',
    english: 'Select the polite request form.',
    correctAnswer: 'てもらえますか',
    options: ['てもらえますか', 'てあげますか', 'てくれますか', 'てもらいますか'],
    explanation: 'てもらえますか is a polite request (could I have you do...?).',
  },

  // ===========================================================================
  // N4 ADJECTIVES
  // ===========================================================================
  // すぎる
  {
    id: 'sugiru-fib-1',
    pattern: 'すぎる',
    type: 'fill_in_blank',
    sentence: 'この料理は辛＿＿＿。',
    english: 'This food is too spicy.',
    correctAnswer: 'すぎる',
    options: ['すぎる', 'そうだ', 'がち', 'っぽい'],
    explanation: 'い-adjective: drop い, add すぎる. 辛い → 辛すぎる.',
  },
  {
    id: 'sugiru-fib-2',
    pattern: 'すぎる',
    type: 'fill_in_blank',
    sentence: '昨日飲み＿＿＿ました。',
    english: 'I drank too much yesterday.',
    correctAnswer: 'すぎ',
    options: ['すぎ', 'たい', 'そう', 'がち'],
    explanation: 'Verb stem + すぎる: 飲み + すぎる → 飲みすぎる.',
  },
  {
    id: 'sugiru-fib-3',
    pattern: 'すぎる',
    type: 'fill_in_blank',
    sentence: 'この部屋は静か＿＿＿る。',
    english: 'This room is too quiet.',
    correctAnswer: 'すぎ',
    options: ['すぎ', 'そう', 'がち', 'みたい'],
    explanation: 'な-adjective: stem + すぎる. 静か + すぎる.',
  },
  {
    id: 'sugiru-mc-1',
    pattern: 'すぎる',
    type: 'multiple_choice',
    sentence: 'How do you attach すぎる to an い-adjective?',
    english: 'Select the correct pattern.',
    correctAnswer: 'Drop い, add すぎる',
    options: ['Drop い, add すぎる', 'Add すぎる directly', 'Change い to く, add すぎる', 'Add さすぎる'],
    explanation: '高い → 高すぎる (drop い, add すぎる).',
  },
  {
    id: 'sugiru-mc-2',
    pattern: 'すぎる',
    type: 'multiple_choice',
    sentence: 'How does すぎる conjugate?',
    english: 'Select the correct answer.',
    correctAnswer: 'As a る-verb (すぎます, すぎた, etc.)',
    options: ['As a る-verb (すぎます, すぎた, etc.)', 'As an い-adjective', 'As a な-adjective', 'It doesn\'t conjugate'],
    explanation: 'すぎる is a る-verb: すぎます, すぎない, すぎた.',
  },
]

export function getExercisesByPattern(pattern: string): GrammarExercise[] {
  return GRAMMAR_EXERCISES.filter((ex) => ex.pattern === pattern)
}

export function getExercisesByPatterns(patterns: string[]): GrammarExercise[] {
  const patternSet = new Set(patterns)
  return GRAMMAR_EXERCISES.filter((ex) => patternSet.has(ex.pattern))
}
