import type { MediaContentData } from '@/types/media'

/**
 * Media Library - Immersion Content
 * 
 * Updated with actual DigitalOcean Spaces CDN URLs
 * Format: https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/[show-name]/[filename].mkv
 * 
 * Total: 6 shows, 239 main episodes + specials, ~122 GB content
 * Subtitles will be extracted and added in future update
 */

export const MEDIA_LIBRARY: MediaContentData[] = [
  // ============================================================================
  // 1. デスノート (Death Note) — Intermediate / N3
  // ============================================================================
  {
    title: 'デスノート',
    title_english: 'Death Note',
    type: 'anime',
    difficulty: 'intermediate',
    jlpt_level: 'N3',
    description:
      'A psychological thriller about a student who finds a supernatural notebook that can kill anyone whose name is written in it. Complex vocabulary around justice, morality, and strategy. Clear enunciation but fast-paced internal monologues and intricate cat-and-mouse games.',
    genres: ['thriller', 'mystery', 'supernatural', 'psychological'],
    streaming_url: 'https://www.crunchyroll.com/series/death-note',
    subtitle_source: 'kitsunekko / OpenSubtitles',
    episodes: [
      {
        episode_number: 1,
        title: '新生',
        title_english: 'Rebirth',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x01_-_Rebirth.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 2,
        title: '対決',
        title_english: 'Confrontation',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x02_-_Confrontation.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 3,
        title: '取引',
        title_english: 'Dealings',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x03_-_Dealings.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 4,
        title: '追跡',
        title_english: 'Pursuit',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x04_-_Pursuit.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 5,
        title: '駆引',
        title_english: 'Tactics',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x05_-_Tactics.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 6,
        title: '綻び',
        title_english: 'Unraveling',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x06_-_Unraveling.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 7,
        title: '曇天',
        title_english: 'Overcast',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x07_-_Overcast.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 8,
        title: '目線',
        title_english: 'Glare',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x08_-_Glare.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 9,
        title: '接触',
        title_english: 'Encounter',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x09_-_Encounter.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 10,
        title: '疑惑',
        title_english: 'Doubt',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x10_-_Doubt.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 11,
        title: '突入',
        title_english: 'Assault',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x11_-_Assault.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 12,
        title: '恋心',
        title_english: 'Love',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x12_-_Love.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 13,
        title: '告白',
        title_english: 'Confession',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x13_-_Confession.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 14,
        title: '友達',
        title_english: 'Friend',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x14_-_Friend.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 15,
        title: '賭け',
        title_english: 'Wager',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x15_-_Wager.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 16,
        title: '決断',
        title_english: 'Decision',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x16_-_Decision.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 17,
        title: '執行',
        title_english: 'Execution',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x17_-_Execution.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 18,
        title: '仲間',
        title_english: 'Ally',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x18_-_Ally.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 19,
        title: '松田',
        title_english: 'Matsuda',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x19_-_Matsuda.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 20,
        title: '姑息',
        title_english: 'Makeshift',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x20_-_Makeshift.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 21,
        title: '活動',
        title_english: 'Performance',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x21_-_Performance.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 22,
        title: '誘導',
        title_english: 'Guidance',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x22_-_Guidance.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 23,
        title: '狂騒',
        title_english: 'Frenzy',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x23_-_Frenzy.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 24,
        title: '復活',
        title_english: 'Revival',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x24_-_Revival.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 25,
        title: '沈黙',
        title_english: 'Silence',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x25_-_Silence.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 26,
        title: '再生',
        title_english: 'Renewal',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x26_-_Renewal.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 27,
        title: '誘拐',
        title_english: 'Abduction',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x27_-_Abduction.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 28,
        title: '焦燥',
        title_english: 'Impatience',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x28_-_Impatience.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 29,
        title: '父親',
        title_english: 'Father',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x29_-_Father.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 30,
        title: '正義',
        title_english: 'Justice',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x30_-_Justice.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 31,
        title: '移譲',
        title_english: 'Transfer',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x31_-_Transfer.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 32,
        title: '選択',
        title_english: 'Selection',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x32_-_Selection.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 33,
        title: '嘲笑',
        title_english: 'Scorn',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x33_-_Scorn.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 34,
        title: '警戒',
        title_english: 'Vigilance',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x34_-_Vigilance.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 35,
        title: '殺意',
        title_english: 'Malice',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x35_-_Malice.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 36,
        title: '1.28',
        title_english: '1.28',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x36_-_1.28.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 37,
        title: '新世界',
        title_english: 'New World',
        duration_seconds: 1380,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/death-note/Death_Note_-_01x37_-_New_World.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
    ],
  },

  // ============================================================================
  // 2. ハイキュー!! (Haikyuu!!) — Beginner / N4
  // ============================================================================
  {
    title: 'ハイキュー!!',
    title_english: 'Haikyuu!!',
    type: 'anime',
    difficulty: 'beginner',
    jlpt_level: 'N4',
    description:
      'A high school volleyball anime following a determined boy and his talented setter teammate. Clear, energetic sports dialogue with repeated volleyball terminology. Great for learning sports vocabulary and team dynamics expressions.',
    genres: ['sports', 'school', 'comedy', 'drama'],
    streaming_url: 'https://www.crunchyroll.com/series/haikyu',
    subtitle_source: 'kitsunekko / community',
    episodes: [
      {
        episode_number: 1,
        title: '第1話',
        title_english: 'Episode 1',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_01.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 2,
        title: '第2話',
        title_english: 'Episode 2',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_02.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 3,
        title: '第3話',
        title_english: 'Episode 3',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_03.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 4,
        title: '第4話',
        title_english: 'Episode 4',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_04.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 5,
        title: '第5話',
        title_english: 'Episode 5',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_05.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 6,
        title: '第6話',
        title_english: 'Episode 6',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_06.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 7,
        title: '第7話',
        title_english: 'Episode 7',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_07.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 8,
        title: '第8話',
        title_english: 'Episode 8',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_08.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 9,
        title: '第9話',
        title_english: 'Episode 9',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_09.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 10,
        title: '第10話',
        title_english: 'Episode 10',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_10.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 11,
        title: '第11話',
        title_english: 'Episode 11',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_11.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 12,
        title: '第12話',
        title_english: 'Episode 12',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_12.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 13,
        title: '第13話',
        title_english: 'Episode 13',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_13.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 14,
        title: '第14話',
        title_english: 'Episode 14',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_14.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 15,
        title: '第15話',
        title_english: 'Episode 15',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_15.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 16,
        title: '第16話',
        title_english: 'Episode 16',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_16.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 17,
        title: '第17話',
        title_english: 'Episode 17',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_17.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 18,
        title: '第18話',
        title_english: 'Episode 18',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_18.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 19,
        title: '第19話',
        title_english: 'Episode 19',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_19.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 20,
        title: '第20話',
        title_english: 'Episode 20',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_20.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 21,
        title: '第21話',
        title_english: 'Episode 21',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_21.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 22,
        title: '第22話',
        title_english: 'Episode 22',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_22.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 23,
        title: '第23話',
        title_english: 'Episode 23',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_23.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 24,
        title: '第24話',
        title_english: 'Episode 24',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_24.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 25,
        title: '第25話',
        title_english: 'Episode 25',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/haikyuu/Haikyuu!!_-_25.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
    ],
  },

  // ============================================================================
  // 3. 湾岸ミッドナイト (Wangan Midnight) — Intermediate / N3
  // ============================================================================
  {
    title: '湾岸ミッドナイト',
    title_english: 'Wangan Midnight',
    type: 'anime',
    difficulty: 'intermediate',
    jlpt_level: 'N3',
    description:
      'A street racing anime about a young man and his legendary Devil Z. Features car terminology, racing slang, and technical vocabulary. Fast-paced dialogue during races with mechanical and automotive terms.',
    genres: ['racing', 'sports', 'drama', 'seinen'],
    streaming_url: 'https://www.crunchyroll.com/series/wangan-midnight',
    subtitle_source: 'community',
    episodes: [
      {
        episode_number: 1,
        title: '第1話',
        title_english: 'Episode 1',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_01_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 2,
        title: '第2話',
        title_english: 'Episode 2',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_02_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 3,
        title: '第3話',
        title_english: 'Episode 3',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_03_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 4,
        title: '第4話',
        title_english: 'Episode 4',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_04_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 5,
        title: '第5話',
        title_english: 'Episode 5',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_05_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 6,
        title: '第6話',
        title_english: 'Episode 6',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_06_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 7,
        title: '第7話',
        title_english: 'Episode 7',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_07_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 8,
        title: '第8話',
        title_english: 'Episode 8',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_08_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 9,
        title: '第9話',
        title_english: 'Episode 9',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_09_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 10,
        title: '第10話',
        title_english: 'Episode 10',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_10_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 11,
        title: '第11話',
        title_english: 'Episode 11',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_11_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 12,
        title: '第12話',
        title_english: 'Episode 12',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_12_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 13,
        title: '第13話',
        title_english: 'Episode 13',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_13_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 14,
        title: '第14話',
        title_english: 'Episode 14',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_14_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 15,
        title: '第15話',
        title_english: 'Episode 15',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_15_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 16,
        title: '第16話',
        title_english: 'Episode 16',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_16_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 17,
        title: '第17話',
        title_english: 'Episode 17',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_17_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 18,
        title: '第18話',
        title_english: 'Episode 18',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_18_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 19,
        title: '第19話',
        title_english: 'Episode 19',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_19_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 20,
        title: '第20話',
        title_english: 'Episode 20',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_20_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 21,
        title: '第21話',
        title_english: 'Episode 21',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_21_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 22,
        title: '第22話',
        title_english: 'Episode 22',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_22_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 23,
        title: '第23話',
        title_english: 'Episode 23',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_23_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 24,
        title: '第24話',
        title_english: 'Episode 24',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_24_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 25,
        title: '第25話',
        title_english: 'Episode 25',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_25_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 26,
        title: '第26話',
        title_english: 'Episode 26',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/wangan-midnight/Wangan_Midnight_-_26_(DVD_480p_x265_AAC)_.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
    ],
  },

  // ============================================================================
  // 4. 頭文字D (Initial D) — Intermediate / N3
  // ============================================================================
  {
    title: '頭文字D',
    title_english: 'Initial D',
    type: 'anime',
    difficulty: 'intermediate',
    jlpt_level: 'N3',
    description:
      'The legendary tofu delivery driver turned street racer. Heavy car terminology, racing strategy, and Gunma dialect. Technical vocabulary about drift racing, engine modifications, and racing techniques.',
    genres: ['racing', 'sports', 'drama', 'seinen'],
    streaming_url: 'https://www.funimation.com/shows/initial-d',
    subtitle_source: 'community',
    episodes: [
      {
        episode_number: 1,
        title: '第1話',
        title_english: 'First Stage Episode 1',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E01.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 2,
        title: '第2話',
        title_english: 'First Stage Episode 2',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E02.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 3,
        title: '第3話',
        title_english: 'First Stage Episode 3',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E03.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 4,
        title: '第4話',
        title_english: 'First Stage Episode 4',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E04.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 5,
        title: '第5話',
        title_english: 'First Stage Episode 5',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E05.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 6,
        title: '第6話',
        title_english: 'First Stage Episode 6',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E06.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 7,
        title: '第7話',
        title_english: 'First Stage Episode 7',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E07.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 8,
        title: '第8話',
        title_english: 'First Stage Episode 8',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E08.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 9,
        title: '第9話',
        title_english: 'First Stage Episode 9',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E09.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 10,
        title: '第10話',
        title_english: 'First Stage Episode 10',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E10.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 11,
        title: '第11話',
        title_english: 'First Stage Episode 11',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E11.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 12,
        title: '第12話',
        title_english: 'First Stage Episode 12',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E12.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 13,
        title: '第13話',
        title_english: 'First Stage Episode 13',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E13.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 14,
        title: '第14話',
        title_english: 'First Stage Episode 14',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E14.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 15,
        title: '第15話',
        title_english: 'First Stage Episode 15',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E15.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 17,
        title: '第17話',
        title_english: 'First Stage Episode 17',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E17.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 18,
        title: '第18話',
        title_english: 'First Stage Episode 18',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E18.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 19,
        title: '第19話',
        title_english: 'First Stage Episode 19',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E19.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 20,
        title: '第20話',
        title_english: 'First Stage Episode 20',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E20.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 21,
        title: '第21話',
        title_english: 'First Stage Episode 21',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E21.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 22,
        title: '第22話',
        title_english: 'First Stage Episode 22',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E22.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 23,
        title: '第23話',
        title_english: 'First Stage Episode 23',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E23.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 24,
        title: '第24話',
        title_english: 'First Stage Episode 24',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E24.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 25,
        title: '第25話',
        title_english: 'First Stage Episode 25',
        duration_seconds: 1500,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/initial-d/Initial_D_-_S01E25.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
    ],
  },

  // ============================================================================
  // 5. 食戟のソーマ (Food Wars! Shokugeki no Soma) — Intermediate / N3
  // ============================================================================
  {
    title: '食戟のソーマ',
    title_english: 'Food Wars! Shokugeki no Soma',
    type: 'anime',
    difficulty: 'intermediate',
    jlpt_level: 'N3',
    description:
      'A cooking battle anime following a young chef at an elite culinary school. Rich food terminology, cooking techniques, and ingredient names. Energetic shonen-style dialogue mixed with detailed culinary vocabulary.',
    genres: ['cooking', 'school', 'comedy', 'ecchi'],
    streaming_url: 'https://www.crunchyroll.com/series/food-wars-shokugeki-no-soma',
    subtitle_source: 'kitsunekko / community',
    episodes: [
      {
        episode_number: 1,
        title: '第1話',
        title_english: 'Episode 1',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/food-wars/Food_Wars_-_01.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 2,
        title: '第2話',
        title_english: 'Episode 2',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/food-wars/Food_Wars_-_02.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 3,
        title: '第3話',
        title_english: 'Episode 3',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/food-wars/Food_Wars_-_03.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 4,
        title: '第4話',
        title_english: 'Episode 4',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/food-wars/Food_Wars_-_04.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 5,
        title: '第5話',
        title_english: 'Episode 5',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/food-wars/Food_Wars_-_05.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 6,
        title: '第6話',
        title_english: 'Episode 6',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/food-wars/Food_Wars_-_06.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 7,
        title: '第7話',
        title_english: 'Episode 7',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/food-wars/Food_Wars_-_07.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 8,
        title: '第8話',
        title_english: 'Episode 8',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/food-wars/Food_Wars_-_08.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 9,
        title: '第9話',
        title_english: 'Episode 9',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/food-wars/Food_Wars_-_09.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 10,
        title: '第10話',
        title_english: 'Episode 10',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/food-wars/Food_Wars_-_10.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 11,
        title: '第11話',
        title_english: 'Episode 11',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/food-wars/Food_Wars_-_11.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
      {
        episode_number: 12,
        title: '第12話',
        title_english: 'Episode 12',
        duration_seconds: 1440,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/food-wars/Food_Wars_-_12.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
    ],
  },

  // ============================================================================
  // 6. オッドタクシー (Odd Taxi) — Intermediate / N3
  // ============================================================================
  {
    title: 'オッドタクシー',
    title_english: 'Odd Taxi',
    type: 'anime',
    difficulty: 'intermediate',
    jlpt_level: 'N3',
    description:
      'A mystery thriller following a walrus taxi driver in Tokyo. Natural conversational Japanese with various character dialects. Complex narrative with layered dialogue and urban slang.',
    genres: ['mystery', 'thriller', 'slice-of-life', 'psychological'],
    streaming_url: 'https://www.crunchyroll.com/series/odd-taxi',
    subtitle_source: 'community',
    episodes: [
      {
        episode_number: 1,
        title: '全話',
        title_english: 'Complete Series',
        duration_seconds: 15600,
        video_url: 'https://wakaru-media.sfo3.cdn.digitaloceanspaces.com/videos/odd-taxi/.mkv',
        subtitle_ja_url: null,
        subtitle_en_url: null,
      },
    ],
  },

]

